// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: community.proto

package communityrpc

import (
	"context"

	"smartcommunity-microservices/app/community/rpc/types/community"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignParkingReq       = community.AssignParkingReq
	AuditVisitorReq        = community.AuditVisitorReq
	BaseResp               = community.BaseResp
	BindPlateReq           = community.BindPlateReq
	CreateNoticeReq        = community.CreateNoticeReq
	CreateParkingReq       = community.CreateParkingReq
	CreatePropertyFeeReq   = community.CreatePropertyFeeReq
	CreateVisitorReq       = community.CreateVisitorReq
	ListMessagesReq        = community.ListMessagesReq
	ListNoticesReq         = community.ListNoticesReq
	ListParkingReq         = community.ListParkingReq
	ListPaymentsReq        = community.ListPaymentsReq
	ListPropertyFeesReq    = community.ListPropertyFeesReq
	ListVisitorReq         = community.ListVisitorReq
	MessageInfo            = community.MessageInfo
	MessageListResp        = community.MessageListResp
	NoticeDetailResp       = community.NoticeDetailResp
	NoticeIDReq            = community.NoticeIDReq
	NoticeInfo             = community.NoticeInfo
	NoticeListResp         = community.NoticeListResp
	NoticeViewsResp        = community.NoticeViewsResp
	ParkingListResp        = community.ParkingListResp
	ParkingSpaceInfo       = community.ParkingSpaceInfo
	ParkingStatsResp       = community.ParkingStatsResp
	PayPropertyFeeReq      = community.PayPropertyFeeReq
	PaymentListResp        = community.PaymentListResp
	PropertyFeeInfo        = community.PropertyFeeInfo
	PropertyFeeListResp    = community.PropertyFeeListResp
	PropertyFeePaymentInfo = community.PropertyFeePaymentInfo
	SendMessageReq         = community.SendMessageReq
	UserIDReq              = community.UserIDReq
	VisitorInfo            = community.VisitorInfo
	VisitorListResp        = community.VisitorListResp

	CommunityRpc interface {
		ListNotices(ctx context.Context, in *ListNoticesReq, opts ...grpc.CallOption) (*NoticeListResp, error)
		GetNoticeDetail(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*NoticeDetailResp, error)
		MarkNoticeRead(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*BaseResp, error)
		AdminListNotices(ctx context.Context, in *ListNoticesReq, opts ...grpc.CallOption) (*NoticeListResp, error)
		CreateNotice(ctx context.Context, in *CreateNoticeReq, opts ...grpc.CallOption) (*BaseResp, error)
		DeleteNotice(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetNoticeViews(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*NoticeViewsResp, error)
		CreateVisitor(ctx context.Context, in *CreateVisitorReq, opts ...grpc.CallOption) (*BaseResp, error)
		ListMyVisitors(ctx context.Context, in *ListVisitorReq, opts ...grpc.CallOption) (*VisitorListResp, error)
		AdminListVisitors(ctx context.Context, in *ListVisitorReq, opts ...grpc.CallOption) (*VisitorListResp, error)
		AuditVisitor(ctx context.Context, in *AuditVisitorReq, opts ...grpc.CallOption) (*BaseResp, error)
		ListMyParking(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*ParkingListResp, error)
		BindPlate(ctx context.Context, in *BindPlateReq, opts ...grpc.CallOption) (*BaseResp, error)
		AdminListParking(ctx context.Context, in *ListParkingReq, opts ...grpc.CallOption) (*ParkingListResp, error)
		CreateParking(ctx context.Context, in *CreateParkingReq, opts ...grpc.CallOption) (*BaseResp, error)
		AssignParking(ctx context.Context, in *AssignParkingReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetParkingStats(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*ParkingStatsResp, error)
		ListMyFees(ctx context.Context, in *ListPropertyFeesReq, opts ...grpc.CallOption) (*PropertyFeeListResp, error)
		PayPropertyFee(ctx context.Context, in *PayPropertyFeeReq, opts ...grpc.CallOption) (*BaseResp, error)
		ListMyPayments(ctx context.Context, in *ListPaymentsReq, opts ...grpc.CallOption) (*PaymentListResp, error)
		AdminListFees(ctx context.Context, in *ListPropertyFeesReq, opts ...grpc.CallOption) (*PropertyFeeListResp, error)
		AdminCreateFee(ctx context.Context, in *CreatePropertyFeeReq, opts ...grpc.CallOption) (*BaseResp, error)
		AdminListPayments(ctx context.Context, in *ListPaymentsReq, opts ...grpc.CallOption) (*PaymentListResp, error)
		ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*MessageListResp, error)
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultCommunityRpc struct {
		cli zrpc.Client
	}
)

func NewCommunityRpc(cli zrpc.Client) CommunityRpc {
	return &defaultCommunityRpc{
		cli: cli,
	}
}

func (m *defaultCommunityRpc) ListNotices(ctx context.Context, in *ListNoticesReq, opts ...grpc.CallOption) (*NoticeListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.ListNotices(ctx, in, opts...)
}

func (m *defaultCommunityRpc) GetNoticeDetail(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*NoticeDetailResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.GetNoticeDetail(ctx, in, opts...)
}

func (m *defaultCommunityRpc) MarkNoticeRead(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.MarkNoticeRead(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AdminListNotices(ctx context.Context, in *ListNoticesReq, opts ...grpc.CallOption) (*NoticeListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AdminListNotices(ctx, in, opts...)
}

func (m *defaultCommunityRpc) CreateNotice(ctx context.Context, in *CreateNoticeReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.CreateNotice(ctx, in, opts...)
}

func (m *defaultCommunityRpc) DeleteNotice(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.DeleteNotice(ctx, in, opts...)
}

func (m *defaultCommunityRpc) GetNoticeViews(ctx context.Context, in *NoticeIDReq, opts ...grpc.CallOption) (*NoticeViewsResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.GetNoticeViews(ctx, in, opts...)
}

func (m *defaultCommunityRpc) CreateVisitor(ctx context.Context, in *CreateVisitorReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.CreateVisitor(ctx, in, opts...)
}

func (m *defaultCommunityRpc) ListMyVisitors(ctx context.Context, in *ListVisitorReq, opts ...grpc.CallOption) (*VisitorListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.ListMyVisitors(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AdminListVisitors(ctx context.Context, in *ListVisitorReq, opts ...grpc.CallOption) (*VisitorListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AdminListVisitors(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AuditVisitor(ctx context.Context, in *AuditVisitorReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AuditVisitor(ctx, in, opts...)
}

func (m *defaultCommunityRpc) ListMyParking(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*ParkingListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.ListMyParking(ctx, in, opts...)
}

func (m *defaultCommunityRpc) BindPlate(ctx context.Context, in *BindPlateReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.BindPlate(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AdminListParking(ctx context.Context, in *ListParkingReq, opts ...grpc.CallOption) (*ParkingListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AdminListParking(ctx, in, opts...)
}

func (m *defaultCommunityRpc) CreateParking(ctx context.Context, in *CreateParkingReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.CreateParking(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AssignParking(ctx context.Context, in *AssignParkingReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AssignParking(ctx, in, opts...)
}

func (m *defaultCommunityRpc) GetParkingStats(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*ParkingStatsResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.GetParkingStats(ctx, in, opts...)
}

func (m *defaultCommunityRpc) ListMyFees(ctx context.Context, in *ListPropertyFeesReq, opts ...grpc.CallOption) (*PropertyFeeListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.ListMyFees(ctx, in, opts...)
}

func (m *defaultCommunityRpc) PayPropertyFee(ctx context.Context, in *PayPropertyFeeReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.PayPropertyFee(ctx, in, opts...)
}

func (m *defaultCommunityRpc) ListMyPayments(ctx context.Context, in *ListPaymentsReq, opts ...grpc.CallOption) (*PaymentListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.ListMyPayments(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AdminListFees(ctx context.Context, in *ListPropertyFeesReq, opts ...grpc.CallOption) (*PropertyFeeListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AdminListFees(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AdminCreateFee(ctx context.Context, in *CreatePropertyFeeReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AdminCreateFee(ctx, in, opts...)
}

func (m *defaultCommunityRpc) AdminListPayments(ctx context.Context, in *ListPaymentsReq, opts ...grpc.CallOption) (*PaymentListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.AdminListPayments(ctx, in, opts...)
}

func (m *defaultCommunityRpc) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*MessageListResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

func (m *defaultCommunityRpc) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := community.NewCommunityRpcClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}
