// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stats.proto

package statsrpc

import (
	"context"

	"smartcommunity-microservices/app/stats/rpc/types/stats"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AIReportInfo          = stats.AIReportInfo
	BaseResp              = stats.BaseResp
	CommunityOverviewResp = stats.CommunityOverviewResp
	DaysReq               = stats.DaysReq
	GenerateReportReq     = stats.GenerateReportReq
	ListReportsReq        = stats.ListReportsReq
	OrderStatsResp        = stats.OrderStatsResp
	OrderSummaryInfo      = stats.OrderSummaryInfo
	OrderTrendInfo        = stats.OrderTrendInfo
	RankLimitReq          = stats.RankLimitReq
	ReportIDReq           = stats.ReportIDReq
	ReportListResp        = stats.ReportListResp
	ReportResp            = stats.ReportResp
	SalesRankInfo         = stats.SalesRankInfo
	SalesRankResp         = stats.SalesRankResp
	ViewRankInfo          = stats.ViewRankInfo
	ViewRankResp          = stats.ViewRankResp
	WorkorderStatsResp    = stats.WorkorderStatsResp
	WorkorderSummaryInfo  = stats.WorkorderSummaryInfo

	StatsRpc interface {
		GetProductSalesRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*SalesRankResp, error)
		GetProductViewRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*ViewRankResp, error)
		GetCommunityOverview(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*CommunityOverviewResp, error)
		GetOrderStatsCombined(ctx context.Context, in *DaysReq, opts ...grpc.CallOption) (*OrderStatsResp, error)
		GetWorkorderStats(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*WorkorderStatsResp, error)
		GenerateAIReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*ReportResp, error)
		GetLatestAIReport(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*ReportResp, error)
		ListAIReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ReportListResp, error)
		GetAIReportDetail(ctx context.Context, in *ReportIDReq, opts ...grpc.CallOption) (*ReportResp, error)
	}

	defaultStatsRpc struct {
		cli zrpc.Client
	}
)

func NewStatsRpc(cli zrpc.Client) StatsRpc {
	return &defaultStatsRpc{
		cli: cli,
	}
}

func (m *defaultStatsRpc) GetProductSalesRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*SalesRankResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetProductSalesRank(ctx, in, opts...)
}

func (m *defaultStatsRpc) GetProductViewRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*ViewRankResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetProductViewRank(ctx, in, opts...)
}

func (m *defaultStatsRpc) GetCommunityOverview(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*CommunityOverviewResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetCommunityOverview(ctx, in, opts...)
}

func (m *defaultStatsRpc) GetOrderStatsCombined(ctx context.Context, in *DaysReq, opts ...grpc.CallOption) (*OrderStatsResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetOrderStatsCombined(ctx, in, opts...)
}

func (m *defaultStatsRpc) GetWorkorderStats(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*WorkorderStatsResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetWorkorderStats(ctx, in, opts...)
}

func (m *defaultStatsRpc) GenerateAIReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*ReportResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GenerateAIReport(ctx, in, opts...)
}

func (m *defaultStatsRpc) GetLatestAIReport(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*ReportResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetLatestAIReport(ctx, in, opts...)
}

func (m *defaultStatsRpc) ListAIReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ReportListResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.ListAIReports(ctx, in, opts...)
}

func (m *defaultStatsRpc) GetAIReportDetail(ctx context.Context, in *ReportIDReq, opts ...grpc.CallOption) (*ReportResp, error) {
	client := stats.NewStatsRpcClient(m.cli.Conn())
	return client.GetAIReportDetail(ctx, in, opts...)
}
