server {
    listen 81;
    server_name localhost;
    client_max_body_size 20m;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

        # 强制浏览器不缓存 HTML 页面，防因哈希失效产生 502/MIME 报错
        if ($request_filename ~* .*\.(html|htm)$) {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }

    location /api/ {
        proxy_pass http://gateway-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 10s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;
    }

    location /agent/ {
        proxy_pass http://gateway-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 10s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;
    }
}
