apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-community-ingress
  namespace: smart-community
spec:
  rules:
    - host: smart-community.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8000
