// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: workorder.proto

package workorderrpc

import (
	"context"

	"smartcommunity-microservices/app/workorder/rpc/types/workorder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp            = workorder.BaseResp
	CreateWorkorderReq  = workorder.CreateWorkorderReq
	GetLogsReq          = workorder.GetLogsReq
	ListWorkorderReq    = workorder.ListWorkorderReq
	LogListResp         = workorder.LogListResp
	ProcessWorkorderReq = workorder.ProcessWorkorderReq
	WorkorderInfo       = workorder.WorkorderInfo
	WorkorderListResp   = workorder.WorkorderListResp
	WorkorderLogInfo    = workorder.WorkorderLogInfo

	WorkorderRpc interface {
		CreateWorkorder(ctx context.Context, in *CreateWorkorderReq, opts ...grpc.CallOption) (*BaseResp, error)
		ListMyWorkorders(ctx context.Context, in *ListWorkorderReq, opts ...grpc.CallOption) (*WorkorderListResp, error)
		GetWorkorderLogs(ctx context.Context, in *GetLogsReq, opts ...grpc.CallOption) (*LogListResp, error)
		AdminListWorkorders(ctx context.Context, in *ListWorkorderReq, opts ...grpc.CallOption) (*WorkorderListResp, error)
		AdminProcessWorkorder(ctx context.Context, in *ProcessWorkorderReq, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultWorkorderRpc struct {
		cli zrpc.Client
	}
)

func NewWorkorderRpc(cli zrpc.Client) WorkorderRpc {
	return &defaultWorkorderRpc{
		cli: cli,
	}
}

func (m *defaultWorkorderRpc) CreateWorkorder(ctx context.Context, in *CreateWorkorderReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := workorder.NewWorkorderRpcClient(m.cli.Conn())
	return client.CreateWorkorder(ctx, in, opts...)
}

func (m *defaultWorkorderRpc) ListMyWorkorders(ctx context.Context, in *ListWorkorderReq, opts ...grpc.CallOption) (*WorkorderListResp, error) {
	client := workorder.NewWorkorderRpcClient(m.cli.Conn())
	return client.ListMyWorkorders(ctx, in, opts...)
}

func (m *defaultWorkorderRpc) GetWorkorderLogs(ctx context.Context, in *GetLogsReq, opts ...grpc.CallOption) (*LogListResp, error) {
	client := workorder.NewWorkorderRpcClient(m.cli.Conn())
	return client.GetWorkorderLogs(ctx, in, opts...)
}

func (m *defaultWorkorderRpc) AdminListWorkorders(ctx context.Context, in *ListWorkorderReq, opts ...grpc.CallOption) (*WorkorderListResp, error) {
	client := workorder.NewWorkorderRpcClient(m.cli.Conn())
	return client.AdminListWorkorders(ctx, in, opts...)
}

func (m *defaultWorkorderRpc) AdminProcessWorkorder(ctx context.Context, in *ProcessWorkorderReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := workorder.NewWorkorderRpcClient(m.cli.Conn())
	return client.AdminProcessWorkorder(ctx, in, opts...)
}
