apiVersion: v1
kind: Secret
metadata:
  name: smart-community-dev-secrets
  namespace: smart-community
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123456
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  LLM_API_KEY: ""
