// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package agentrpc

import (
	"context"

	"smartcommunity-microservices/app/agent/rpc/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApproveActionReq      = agent.ApproveActionReq
	ApproveActionResp     = agent.ApproveActionResp
	BaseResp              = agent.BaseResp
	ChatReq               = agent.ChatReq
	ChatResp              = agent.ChatResp
	ConversationInfo      = agent.ConversationInfo
	CreateConversationReq = agent.CreateConversationReq
	DeleteConversationReq = agent.DeleteConversationReq
	GetChatHistoryReq     = agent.GetChatHistoryReq
	GetChatHistoryResp    = agent.GetChatHistoryResp
	ListConversationsReq  = agent.ListConversationsReq
	ListConversationsResp = agent.ListConversationsResp
	MessageInfo           = agent.MessageInfo
	RejectActionReq       = agent.RejectActionReq

	AgentRpc interface {
		CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*ConversationInfo, error)
		DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*BaseResp, error)
		ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error)
		GetChatHistory(ctx context.Context, in *GetChatHistoryReq, opts ...grpc.CallOption) (*GetChatHistoryResp, error)
		ChatStream(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (agent.AgentRpc_ChatStreamClient, error)
		ApproveAction(ctx context.Context, in *ApproveActionReq, opts ...grpc.CallOption) (*ApproveActionResp, error)
		RejectAction(ctx context.Context, in *RejectActionReq, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultAgentRpc struct {
		cli zrpc.Client
	}
)

func NewAgentRpc(cli zrpc.Client) AgentRpc {
	return &defaultAgentRpc{
		cli: cli,
	}
}

func (m *defaultAgentRpc) CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*ConversationInfo, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.CreateConversation(ctx, in, opts...)
}

func (m *defaultAgentRpc) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.DeleteConversation(ctx, in, opts...)
}

func (m *defaultAgentRpc) ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

func (m *defaultAgentRpc) GetChatHistory(ctx context.Context, in *GetChatHistoryReq, opts ...grpc.CallOption) (*GetChatHistoryResp, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.GetChatHistory(ctx, in, opts...)
}

func (m *defaultAgentRpc) ChatStream(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (agent.AgentRpc_ChatStreamClient, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.ChatStream(ctx, in, opts...)
}

func (m *defaultAgentRpc) ApproveAction(ctx context.Context, in *ApproveActionReq, opts ...grpc.CallOption) (*ApproveActionResp, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.ApproveAction(ctx, in, opts...)
}

func (m *defaultAgentRpc) RejectAction(ctx context.Context, in *RejectActionReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := agent.NewAgentRpcClient(m.cli.Conn())
	return client.RejectAction(ctx, in, opts...)
}
