// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package server

import (
	"context"

	"smartcommunity-microservices/app/agent/rpc/agent"
	"smartcommunity-microservices/app/agent/rpc/internal/logic"
	"smartcommunity-microservices/app/agent/rpc/internal/svc"
)

type AgentRpcServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentRpcServer
}

func NewAgentRpcServer(svcCtx *svc.ServiceContext) *AgentRpcServer {
	return &AgentRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentRpcServer) CreateConversation(ctx context.Context, in *agent.CreateConversationReq) (*agent.ConversationInfo, error) {
	l := logic.NewCreateConversationLogic(ctx, s.svcCtx)
	return l.CreateConversation(in)
}

func (s *AgentRpcServer) DeleteConversation(ctx context.Context, in *agent.DeleteConversationReq) (*agent.BaseResp, error) {
	l := logic.NewDeleteConversationLogic(ctx, s.svcCtx)
	return l.DeleteConversation(in)
}

func (s *AgentRpcServer) ListConversations(ctx context.Context, in *agent.ListConversationsReq) (*agent.ListConversationsResp, error) {
	l := logic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *AgentRpcServer) GetChatHistory(ctx context.Context, in *agent.GetChatHistoryReq) (*agent.GetChatHistoryResp, error) {
	l := logic.NewGetChatHistoryLogic(ctx, s.svcCtx)
	return l.GetChatHistory(in)
}

func (s *AgentRpcServer) ChatStream(in *agent.ChatReq, stream agent.AgentRpc_ChatStreamServer) error {
	l := logic.NewChatStreamLogic(stream.Context(), s.svcCtx)
	return l.ChatStream(in, stream)
}

func (s *AgentRpcServer) ApproveAction(ctx context.Context, in *agent.ApproveActionReq) (*agent.ApproveActionResp, error) {
	l := logic.NewApproveActionLogic(ctx, s.svcCtx)
	return l.ApproveAction(in)
}

func (s *AgentRpcServer) RejectAction(ctx context.Context, in *agent.RejectActionReq) (*agent.BaseResp, error) {
	l := logic.NewRejectActionLogic(ctx, s.svcCtx)
	return l.RejectAction(in)
}
