// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: app/community/rpc/community.proto

package community

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDReq) Reset() {
	*x = UserIDReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDReq) ProtoMessage() {}

func (x *UserIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDReq.ProtoReflect.Descriptor instead.
func (*UserIDReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{1}
}

func (x *UserIDReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Notices
type NoticeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Publisher     string                 `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	ViewCount     int64                  `protobuf:"varint,5,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeInfo) Reset() {
	*x = NoticeInfo{}
	mi := &file_app_community_rpc_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeInfo) ProtoMessage() {}

func (x *NoticeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeInfo.ProtoReflect.Descriptor instead.
func (*NoticeInfo) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{2}
}

func (x *NoticeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoticeInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoticeInfo) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *NoticeInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *NoticeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NoticeInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListNoticesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNoticesReq) Reset() {
	*x = ListNoticesReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNoticesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNoticesReq) ProtoMessage() {}

func (x *ListNoticesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNoticesReq.ProtoReflect.Descriptor instead.
func (*ListNoticesReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{3}
}

func (x *ListNoticesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNoticesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type NoticeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*NoticeInfo          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeListResp) Reset() {
	*x = NoticeListResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeListResp) ProtoMessage() {}

func (x *NoticeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeListResp.ProtoReflect.Descriptor instead.
func (*NoticeListResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{4}
}

func (x *NoticeListResp) GetList() []*NoticeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *NoticeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NoticeIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeIDReq) Reset() {
	*x = NoticeIDReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeIDReq) ProtoMessage() {}

func (x *NoticeIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeIDReq.ProtoReflect.Descriptor instead.
func (*NoticeIDReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{5}
}

func (x *NoticeIDReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeIDReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NoticeDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notice        *NoticeInfo            `protobuf:"bytes,1,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeDetailResp) Reset() {
	*x = NoticeDetailResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeDetailResp) ProtoMessage() {}

func (x *NoticeDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeDetailResp.ProtoReflect.Descriptor instead.
func (*NoticeDetailResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{6}
}

func (x *NoticeDetailResp) GetNotice() *NoticeInfo {
	if x != nil {
		return x.Notice
	}
	return nil
}

type NoticeViewsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         int64                  `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeViewsResp) Reset() {
	*x = NoticeViewsResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeViewsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeViewsResp) ProtoMessage() {}

func (x *NoticeViewsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeViewsResp.ProtoReflect.Descriptor instead.
func (*NoticeViewsResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{7}
}

func (x *NoticeViewsResp) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

type CreateNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Publisher     string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoticeReq) Reset() {
	*x = CreateNoticeReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoticeReq) ProtoMessage() {}

func (x *CreateNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoticeReq.ProtoReflect.Descriptor instead.
func (*CreateNoticeReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{8}
}

func (x *CreateNoticeReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoticeReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateNoticeReq) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

// Visitors
type VisitorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VisitorName   string                 `protobuf:"bytes,3,opt,name=visitor_name,json=visitorName,proto3" json:"visitor_name,omitempty"`
	VisitorPhone  string                 `protobuf:"bytes,4,opt,name=visitor_phone,json=visitorPhone,proto3" json:"visitor_phone,omitempty"`
	VisitPurpose  string                 `protobuf:"bytes,5,opt,name=visit_purpose,json=visitPurpose,proto3" json:"visit_purpose,omitempty"`
	ReleaseTime   string                 `protobuf:"bytes,6,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	ValidDate     string                 `protobuf:"bytes,7,opt,name=valid_date,json=validDate,proto3" json:"valid_date,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	AuditRemark   string                 `protobuf:"bytes,9,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`
	AuditAt       string                 `protobuf:"bytes,10,opt,name=audit_at,json=auditAt,proto3" json:"audit_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserName      string                 `protobuf:"bytes,12,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserMobile    string                 `protobuf:"bytes,13,opt,name=user_mobile,json=userMobile,proto3" json:"user_mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorInfo) Reset() {
	*x = VisitorInfo{}
	mi := &file_app_community_rpc_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorInfo) ProtoMessage() {}

func (x *VisitorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorInfo.ProtoReflect.Descriptor instead.
func (*VisitorInfo) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{9}
}

func (x *VisitorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VisitorInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VisitorInfo) GetVisitorName() string {
	if x != nil {
		return x.VisitorName
	}
	return ""
}

func (x *VisitorInfo) GetVisitorPhone() string {
	if x != nil {
		return x.VisitorPhone
	}
	return ""
}

func (x *VisitorInfo) GetVisitPurpose() string {
	if x != nil {
		return x.VisitPurpose
	}
	return ""
}

func (x *VisitorInfo) GetReleaseTime() string {
	if x != nil {
		return x.ReleaseTime
	}
	return ""
}

func (x *VisitorInfo) GetValidDate() string {
	if x != nil {
		return x.ValidDate
	}
	return ""
}

func (x *VisitorInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VisitorInfo) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

func (x *VisitorInfo) GetAuditAt() string {
	if x != nil {
		return x.AuditAt
	}
	return ""
}

func (x *VisitorInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VisitorInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *VisitorInfo) GetUserMobile() string {
	if x != nil {
		return x.UserMobile
	}
	return ""
}

type CreateVisitorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VisitorName   string                 `protobuf:"bytes,2,opt,name=visitor_name,json=visitorName,proto3" json:"visitor_name,omitempty"`
	VisitorPhone  string                 `protobuf:"bytes,3,opt,name=visitor_phone,json=visitorPhone,proto3" json:"visitor_phone,omitempty"`
	VisitPurpose  string                 `protobuf:"bytes,4,opt,name=visit_purpose,json=visitPurpose,proto3" json:"visit_purpose,omitempty"`
	ReleaseTime   string                 `protobuf:"bytes,5,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	ValidDate     string                 `protobuf:"bytes,6,opt,name=valid_date,json=validDate,proto3" json:"valid_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVisitorReq) Reset() {
	*x = CreateVisitorReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVisitorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVisitorReq) ProtoMessage() {}

func (x *CreateVisitorReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVisitorReq.ProtoReflect.Descriptor instead.
func (*CreateVisitorReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVisitorReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateVisitorReq) GetVisitorName() string {
	if x != nil {
		return x.VisitorName
	}
	return ""
}

func (x *CreateVisitorReq) GetVisitorPhone() string {
	if x != nil {
		return x.VisitorPhone
	}
	return ""
}

func (x *CreateVisitorReq) GetVisitPurpose() string {
	if x != nil {
		return x.VisitPurpose
	}
	return ""
}

func (x *CreateVisitorReq) GetReleaseTime() string {
	if x != nil {
		return x.ReleaseTime
	}
	return ""
}

func (x *CreateVisitorReq) GetValidDate() string {
	if x != nil {
		return x.ValidDate
	}
	return ""
}

type ListVisitorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisitorReq) Reset() {
	*x = ListVisitorReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisitorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisitorReq) ProtoMessage() {}

func (x *ListVisitorReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisitorReq.ProtoReflect.Descriptor instead.
func (*ListVisitorReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{11}
}

func (x *ListVisitorReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListVisitorReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVisitorReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VisitorListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*VisitorInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorListResp) Reset() {
	*x = VisitorListResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorListResp) ProtoMessage() {}

func (x *VisitorListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorListResp.ProtoReflect.Descriptor instead.
func (*VisitorListResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{12}
}

func (x *VisitorListResp) GetList() []*VisitorInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *VisitorListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AuditVisitorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	AuditRemark   string                 `protobuf:"bytes,3,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditVisitorReq) Reset() {
	*x = AuditVisitorReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditVisitorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditVisitorReq) ProtoMessage() {}

func (x *AuditVisitorReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditVisitorReq.ProtoReflect.Descriptor instead.
func (*AuditVisitorReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{13}
}

func (x *AuditVisitorReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditVisitorReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditVisitorReq) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

// Parking
type ParkingSpaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParkingNo     string                 `protobuf:"bytes,2,opt,name=parking_no,json=parkingNo,proto3" json:"parking_no,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserMobile    string                 `protobuf:"bytes,6,opt,name=user_mobile,json=userMobile,proto3" json:"user_mobile,omitempty"`
	CarPlate      string                 `protobuf:"bytes,7,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	BindingId     int64                  `protobuf:"varint,8,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingSpaceInfo) Reset() {
	*x = ParkingSpaceInfo{}
	mi := &file_app_community_rpc_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingSpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingSpaceInfo) ProtoMessage() {}

func (x *ParkingSpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingSpaceInfo.ProtoReflect.Descriptor instead.
func (*ParkingSpaceInfo) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{14}
}

func (x *ParkingSpaceInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParkingSpaceInfo) GetParkingNo() string {
	if x != nil {
		return x.ParkingNo
	}
	return ""
}

func (x *ParkingSpaceInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ParkingSpaceInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ParkingSpaceInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ParkingSpaceInfo) GetUserMobile() string {
	if x != nil {
		return x.UserMobile
	}
	return ""
}

func (x *ParkingSpaceInfo) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *ParkingSpaceInfo) GetBindingId() int64 {
	if x != nil {
		return x.BindingId
	}
	return 0
}

type BindPlateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParkingSpaceId int64                  `protobuf:"varint,2,opt,name=parking_space_id,json=parkingSpaceId,proto3" json:"parking_space_id,omitempty"`
	CarPlate       string                 `protobuf:"bytes,3,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindPlateReq) Reset() {
	*x = BindPlateReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPlateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPlateReq) ProtoMessage() {}

func (x *BindPlateReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPlateReq.ProtoReflect.Descriptor instead.
func (*BindPlateReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{15}
}

func (x *BindPlateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindPlateReq) GetParkingSpaceId() int64 {
	if x != nil {
		return x.ParkingSpaceId
	}
	return 0
}

func (x *BindPlateReq) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

type ListParkingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParkingReq) Reset() {
	*x = ListParkingReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParkingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParkingReq) ProtoMessage() {}

func (x *ListParkingReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParkingReq.ProtoReflect.Descriptor instead.
func (*ListParkingReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{16}
}

func (x *ListParkingReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListParkingReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ParkingListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ParkingSpaceInfo    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingListResp) Reset() {
	*x = ParkingListResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingListResp) ProtoMessage() {}

func (x *ParkingListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingListResp.ProtoReflect.Descriptor instead.
func (*ParkingListResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{17}
}

func (x *ParkingListResp) GetList() []*ParkingSpaceInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ParkingListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateParkingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkingNo     string                 `protobuf:"bytes,1,opt,name=parking_no,json=parkingNo,proto3" json:"parking_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateParkingReq) Reset() {
	*x = CreateParkingReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateParkingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParkingReq) ProtoMessage() {}

func (x *CreateParkingReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParkingReq.ProtoReflect.Descriptor instead.
func (*CreateParkingReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{18}
}

func (x *CreateParkingReq) GetParkingNo() string {
	if x != nil {
		return x.ParkingNo
	}
	return ""
}

type AssignParkingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	CarPlate      string                 `protobuf:"bytes,3,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignParkingReq) Reset() {
	*x = AssignParkingReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignParkingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignParkingReq) ProtoMessage() {}

func (x *AssignParkingReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignParkingReq.ProtoReflect.Descriptor instead.
func (*AssignParkingReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{19}
}

func (x *AssignParkingReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssignParkingReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AssignParkingReq) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

type ParkingStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Bound         int64                  `protobuf:"varint,2,opt,name=bound,proto3" json:"bound,omitempty"`
	Free          int64                  `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkingStatsResp) Reset() {
	*x = ParkingStatsResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkingStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkingStatsResp) ProtoMessage() {}

func (x *ParkingStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkingStatsResp.ProtoReflect.Descriptor instead.
func (*ParkingStatsResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{20}
}

func (x *ParkingStatsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ParkingStatsResp) GetBound() int64 {
	if x != nil {
		return x.Bound
	}
	return 0
}

func (x *ParkingStatsResp) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

// Property Fee
type PropertyFeeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Month         string                 `protobuf:"bytes,3,opt,name=month,proto3" json:"month,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	DueDate       string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	PaidAt        string                 `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyFeeInfo) Reset() {
	*x = PropertyFeeInfo{}
	mi := &file_app_community_rpc_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyFeeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyFeeInfo) ProtoMessage() {}

func (x *PropertyFeeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyFeeInfo.ProtoReflect.Descriptor instead.
func (*PropertyFeeInfo) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{21}
}

func (x *PropertyFeeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PropertyFeeInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PropertyFeeInfo) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *PropertyFeeInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PropertyFeeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PropertyFeeInfo) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *PropertyFeeInfo) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type ListPropertyFeesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertyFeesReq) Reset() {
	*x = ListPropertyFeesReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertyFeesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertyFeesReq) ProtoMessage() {}

func (x *ListPropertyFeesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertyFeesReq.ProtoReflect.Descriptor instead.
func (*ListPropertyFeesReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{22}
}

func (x *ListPropertyFeesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPropertyFeesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPropertyFeesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PropertyFeeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PropertyFeeInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyFeeListResp) Reset() {
	*x = PropertyFeeListResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyFeeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyFeeListResp) ProtoMessage() {}

func (x *PropertyFeeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyFeeListResp.ProtoReflect.Descriptor instead.
func (*PropertyFeeListResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{23}
}

func (x *PropertyFeeListResp) GetList() []*PropertyFeeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PropertyFeeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreatePropertyFeeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	DueDate       string                 `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyFeeReq) Reset() {
	*x = CreatePropertyFeeReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyFeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyFeeReq) ProtoMessage() {}

func (x *CreatePropertyFeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyFeeReq.ProtoReflect.Descriptor instead.
func (*CreatePropertyFeeReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{24}
}

func (x *CreatePropertyFeeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePropertyFeeReq) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CreatePropertyFeeReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePropertyFeeReq) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

type PayPropertyFeeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayPropertyFeeReq) Reset() {
	*x = PayPropertyFeeReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPropertyFeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPropertyFeeReq) ProtoMessage() {}

func (x *PayPropertyFeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPropertyFeeReq.ProtoReflect.Descriptor instead.
func (*PayPropertyFeeReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{25}
}

func (x *PayPropertyFeeReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PayPropertyFeeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PropertyFeePaymentInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertyFeeId       int64                  `protobuf:"varint,2,opt,name=property_fee_id,json=propertyFeeId,proto3" json:"property_fee_id,omitempty"`
	UserId              int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount              float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletTransactionId int64                  `protobuf:"varint,5,opt,name=wallet_transaction_id,json=walletTransactionId,proto3" json:"wallet_transaction_id,omitempty"`
	IdempotencyKey      string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Status              int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	PaidAt              string                 `protobuf:"bytes,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PropertyFeePaymentInfo) Reset() {
	*x = PropertyFeePaymentInfo{}
	mi := &file_app_community_rpc_community_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyFeePaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyFeePaymentInfo) ProtoMessage() {}

func (x *PropertyFeePaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyFeePaymentInfo.ProtoReflect.Descriptor instead.
func (*PropertyFeePaymentInfo) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{26}
}

func (x *PropertyFeePaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PropertyFeePaymentInfo) GetPropertyFeeId() int64 {
	if x != nil {
		return x.PropertyFeeId
	}
	return 0
}

func (x *PropertyFeePaymentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PropertyFeePaymentInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PropertyFeePaymentInfo) GetWalletTransactionId() int64 {
	if x != nil {
		return x.WalletTransactionId
	}
	return 0
}

func (x *PropertyFeePaymentInfo) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PropertyFeePaymentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PropertyFeePaymentInfo) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

type ListPaymentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsReq) Reset() {
	*x = ListPaymentsReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsReq) ProtoMessage() {}

func (x *ListPaymentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsReq.ProtoReflect.Descriptor instead.
func (*ListPaymentsReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{27}
}

func (x *ListPaymentsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPaymentsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PaymentListResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	List          []*PropertyFeePaymentInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentListResp) Reset() {
	*x = PaymentListResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentListResp) ProtoMessage() {}

func (x *PaymentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentListResp.ProtoReflect.Descriptor instead.
func (*PaymentListResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{28}
}

func (x *PaymentListResp) GetList() []*PropertyFeePaymentInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PaymentListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Messages
type MessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_app_community_rpc_community_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{29}
}

func (x *MessageInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MessageInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MessageInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ListMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesReq) Reset() {
	*x = ListMessagesReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReq) ProtoMessage() {}

func (x *ListMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReq.ProtoReflect.Descriptor instead.
func (*ListMessagesReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{30}
}

func (x *ListMessagesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMessagesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MessageListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MessageInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageListResp) Reset() {
	*x = MessageListResp{}
	mi := &file_app_community_rpc_community_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageListResp) ProtoMessage() {}

func (x *MessageListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageListResp.ProtoReflect.Descriptor instead.
func (*MessageListResp) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{31}
}

func (x *MessageListResp) GetList() []*MessageInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MessageListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_app_community_rpc_community_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_community_rpc_community_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_app_community_rpc_community_proto_rawDescGZIP(), []int{32}
}

func (x *SendMessageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_app_community_rpc_community_proto protoreflect.FileDescriptor

const file_app_community_rpc_community_proto_rawDesc = "" +
	"\n" +
	"!app/community/rpc/community.proto\x12\tcommunity\"8\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\tUserIDReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xc0\x01\n" +
	"\n" +
	"NoticeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\tpublisher\x18\x04 \x01(\tR\tpublisher\x12\x1d\n" +
	"\n" +
	"view_count\x18\x05 \x01(\x03R\tviewCount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"8\n" +
	"\x0eListNoticesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"Q\n" +
	"\x0eNoticeListResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.community.NoticeInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"6\n" +
	"\vNoticeIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"A\n" +
	"\x10NoticeDetailResp\x12-\n" +
	"\x06notice\x18\x01 \x01(\v2\x15.community.NoticeInfoR\x06notice\"'\n" +
	"\x0fNoticeViewsResp\x12\x14\n" +
	"\x05views\x18\x01 \x01(\x03R\x05views\"_\n" +
	"\x0fCreateNoticeReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\"\x98\x03\n" +
	"\vVisitorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fvisitor_name\x18\x03 \x01(\tR\vvisitorName\x12#\n" +
	"\rvisitor_phone\x18\x04 \x01(\tR\fvisitorPhone\x12#\n" +
	"\rvisit_purpose\x18\x05 \x01(\tR\fvisitPurpose\x12!\n" +
	"\frelease_time\x18\x06 \x01(\tR\vreleaseTime\x12\x1d\n" +
	"\n" +
	"valid_date\x18\a \x01(\tR\tvalidDate\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12!\n" +
	"\faudit_remark\x18\t \x01(\tR\vauditRemark\x12\x19\n" +
	"\baudit_at\x18\n" +
	" \x01(\tR\aauditAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tuser_name\x18\f \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_mobile\x18\r \x01(\tR\n" +
	"userMobile\"\xda\x01\n" +
	"\x10CreateVisitorReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fvisitor_name\x18\x02 \x01(\tR\vvisitorName\x12#\n" +
	"\rvisitor_phone\x18\x03 \x01(\tR\fvisitorPhone\x12#\n" +
	"\rvisit_purpose\x18\x04 \x01(\tR\fvisitPurpose\x12!\n" +
	"\frelease_time\x18\x05 \x01(\tR\vreleaseTime\x12\x1d\n" +
	"\n" +
	"valid_date\x18\x06 \x01(\tR\tvalidDate\"Q\n" +
	"\x0eListVisitorReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"S\n" +
	"\x0fVisitorListResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.community.VisitorInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\\\n" +
	"\x0fAuditVisitorReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12!\n" +
	"\faudit_remark\x18\x03 \x01(\tR\vauditRemark\"\xec\x01\n" +
	"\x10ParkingSpaceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"parking_no\x18\x02 \x01(\tR\tparkingNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1f\n" +
	"\vuser_mobile\x18\x06 \x01(\tR\n" +
	"userMobile\x12\x1b\n" +
	"\tcar_plate\x18\a \x01(\tR\bcarPlate\x12\x1d\n" +
	"\n" +
	"binding_id\x18\b \x01(\x03R\tbindingId\"n\n" +
	"\fBindPlateReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\x10parking_space_id\x18\x02 \x01(\x03R\x0eparkingSpaceId\x12\x1b\n" +
	"\tcar_plate\x18\x03 \x01(\tR\bcarPlate\"8\n" +
	"\x0eListParkingReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"X\n" +
	"\x0fParkingListResp\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.community.ParkingSpaceInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"1\n" +
	"\x10CreateParkingReq\x12\x1d\n" +
	"\n" +
	"parking_no\x18\x01 \x01(\tR\tparkingNo\"W\n" +
	"\x10AssignParkingReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1b\n" +
	"\tcar_plate\x18\x03 \x01(\tR\bcarPlate\"R\n" +
	"\x10ParkingStatsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05bound\x18\x02 \x01(\x03R\x05bound\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x03R\x04free\"\xb4\x01\n" +
	"\x0fPropertyFeeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05month\x18\x03 \x01(\tR\x05month\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12\x17\n" +
	"\apaid_at\x18\a \x01(\tR\x06paidAt\"V\n" +
	"\x13ListPropertyFeesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"[\n" +
	"\x13PropertyFeeListResp\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.community.PropertyFeeInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"x\n" +
	"\x14CreatePropertyFeeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\tR\adueDate\"<\n" +
	"\x11PayPropertyFeeReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x8f\x02\n" +
	"\x16PropertyFeePaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0fproperty_fee_id\x18\x02 \x01(\x03R\rpropertyFeeId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x122\n" +
	"\x15wallet_transaction_id\x18\x05 \x01(\x03R\x13walletTransactionId\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x17\n" +
	"\apaid_at\x18\b \x01(\tR\x06paidAt\"R\n" +
	"\x0fListPaymentsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"^\n" +
	"\x0fPaymentListResp\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.community.PropertyFeePaymentInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa3\x01\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"9\n" +
	"\x0fListMessagesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"S\n" +
	"\x0fMessageListResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.community.MessageInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"C\n" +
	"\x0eSendMessageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2\xdf\r\n" +
	"\fCommunityRpc\x12C\n" +
	"\vListNotices\x12\x19.community.ListNoticesReq\x1a\x19.community.NoticeListResp\x12F\n" +
	"\x0fGetNoticeDetail\x12\x16.community.NoticeIDReq\x1a\x1b.community.NoticeDetailResp\x12=\n" +
	"\x0eMarkNoticeRead\x12\x16.community.NoticeIDReq\x1a\x13.community.BaseResp\x12H\n" +
	"\x10AdminListNotices\x12\x19.community.ListNoticesReq\x1a\x19.community.NoticeListResp\x12?\n" +
	"\fCreateNotice\x12\x1a.community.CreateNoticeReq\x1a\x13.community.BaseResp\x12;\n" +
	"\fDeleteNotice\x12\x16.community.NoticeIDReq\x1a\x13.community.BaseResp\x12D\n" +
	"\x0eGetNoticeViews\x12\x16.community.NoticeIDReq\x1a\x1a.community.NoticeViewsResp\x12A\n" +
	"\rCreateVisitor\x12\x1b.community.CreateVisitorReq\x1a\x13.community.BaseResp\x12G\n" +
	"\x0eListMyVisitors\x12\x19.community.ListVisitorReq\x1a\x1a.community.VisitorListResp\x12J\n" +
	"\x11AdminListVisitors\x12\x19.community.ListVisitorReq\x1a\x1a.community.VisitorListResp\x12?\n" +
	"\fAuditVisitor\x12\x1a.community.AuditVisitorReq\x1a\x13.community.BaseResp\x12A\n" +
	"\rListMyParking\x12\x14.community.UserIDReq\x1a\x1a.community.ParkingListResp\x129\n" +
	"\tBindPlate\x12\x17.community.BindPlateReq\x1a\x13.community.BaseResp\x12I\n" +
	"\x10AdminListParking\x12\x19.community.ListParkingReq\x1a\x1a.community.ParkingListResp\x12A\n" +
	"\rCreateParking\x12\x1b.community.CreateParkingReq\x1a\x13.community.BaseResp\x12A\n" +
	"\rAssignParking\x12\x1b.community.AssignParkingReq\x1a\x13.community.BaseResp\x12C\n" +
	"\x0fGetParkingStats\x12\x13.community.BaseResp\x1a\x1b.community.ParkingStatsResp\x12L\n" +
	"\n" +
	"ListMyFees\x12\x1e.community.ListPropertyFeesReq\x1a\x1e.community.PropertyFeeListResp\x12C\n" +
	"\x0ePayPropertyFee\x12\x1c.community.PayPropertyFeeReq\x1a\x13.community.BaseResp\x12H\n" +
	"\x0eListMyPayments\x12\x1a.community.ListPaymentsReq\x1a\x1a.community.PaymentListResp\x12O\n" +
	"\rAdminListFees\x12\x1e.community.ListPropertyFeesReq\x1a\x1e.community.PropertyFeeListResp\x12F\n" +
	"\x0eAdminCreateFee\x12\x1f.community.CreatePropertyFeeReq\x1a\x13.community.BaseResp\x12K\n" +
	"\x11AdminListPayments\x12\x1a.community.ListPaymentsReq\x1a\x1a.community.PaymentListResp\x12F\n" +
	"\fListMessages\x12\x1a.community.ListMessagesReq\x1a\x1a.community.MessageListResp\x12=\n" +
	"\vSendMessage\x12\x19.community.SendMessageReq\x1a\x13.community.BaseRespB\rZ\v./communityb\x06proto3"

var (
	file_app_community_rpc_community_proto_rawDescOnce sync.Once
	file_app_community_rpc_community_proto_rawDescData []byte
)

func file_app_community_rpc_community_proto_rawDescGZIP() []byte {
	file_app_community_rpc_community_proto_rawDescOnce.Do(func() {
		file_app_community_rpc_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_community_rpc_community_proto_rawDesc), len(file_app_community_rpc_community_proto_rawDesc)))
	})
	return file_app_community_rpc_community_proto_rawDescData
}

var file_app_community_rpc_community_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_app_community_rpc_community_proto_goTypes = []any{
	(*BaseResp)(nil),               // 0: community.BaseResp
	(*UserIDReq)(nil),              // 1: community.UserIDReq
	(*NoticeInfo)(nil),             // 2: community.NoticeInfo
	(*ListNoticesReq)(nil),         // 3: community.ListNoticesReq
	(*NoticeListResp)(nil),         // 4: community.NoticeListResp
	(*NoticeIDReq)(nil),            // 5: community.NoticeIDReq
	(*NoticeDetailResp)(nil),       // 6: community.NoticeDetailResp
	(*NoticeViewsResp)(nil),        // 7: community.NoticeViewsResp
	(*CreateNoticeReq)(nil),        // 8: community.CreateNoticeReq
	(*VisitorInfo)(nil),            // 9: community.VisitorInfo
	(*CreateVisitorReq)(nil),       // 10: community.CreateVisitorReq
	(*ListVisitorReq)(nil),         // 11: community.ListVisitorReq
	(*VisitorListResp)(nil),        // 12: community.VisitorListResp
	(*AuditVisitorReq)(nil),        // 13: community.AuditVisitorReq
	(*ParkingSpaceInfo)(nil),       // 14: community.ParkingSpaceInfo
	(*BindPlateReq)(nil),           // 15: community.BindPlateReq
	(*ListParkingReq)(nil),         // 16: community.ListParkingReq
	(*ParkingListResp)(nil),        // 17: community.ParkingListResp
	(*CreateParkingReq)(nil),       // 18: community.CreateParkingReq
	(*AssignParkingReq)(nil),       // 19: community.AssignParkingReq
	(*ParkingStatsResp)(nil),       // 20: community.ParkingStatsResp
	(*PropertyFeeInfo)(nil),        // 21: community.PropertyFeeInfo
	(*ListPropertyFeesReq)(nil),    // 22: community.ListPropertyFeesReq
	(*PropertyFeeListResp)(nil),    // 23: community.PropertyFeeListResp
	(*CreatePropertyFeeReq)(nil),   // 24: community.CreatePropertyFeeReq
	(*PayPropertyFeeReq)(nil),      // 25: community.PayPropertyFeeReq
	(*PropertyFeePaymentInfo)(nil), // 26: community.PropertyFeePaymentInfo
	(*ListPaymentsReq)(nil),        // 27: community.ListPaymentsReq
	(*PaymentListResp)(nil),        // 28: community.PaymentListResp
	(*MessageInfo)(nil),            // 29: community.MessageInfo
	(*ListMessagesReq)(nil),        // 30: community.ListMessagesReq
	(*MessageListResp)(nil),        // 31: community.MessageListResp
	(*SendMessageReq)(nil),         // 32: community.SendMessageReq
}
var file_app_community_rpc_community_proto_depIdxs = []int32{
	2,  // 0: community.NoticeListResp.list:type_name -> community.NoticeInfo
	2,  // 1: community.NoticeDetailResp.notice:type_name -> community.NoticeInfo
	9,  // 2: community.VisitorListResp.list:type_name -> community.VisitorInfo
	14, // 3: community.ParkingListResp.list:type_name -> community.ParkingSpaceInfo
	21, // 4: community.PropertyFeeListResp.list:type_name -> community.PropertyFeeInfo
	26, // 5: community.PaymentListResp.list:type_name -> community.PropertyFeePaymentInfo
	29, // 6: community.MessageListResp.list:type_name -> community.MessageInfo
	3,  // 7: community.CommunityRpc.ListNotices:input_type -> community.ListNoticesReq
	5,  // 8: community.CommunityRpc.GetNoticeDetail:input_type -> community.NoticeIDReq
	5,  // 9: community.CommunityRpc.MarkNoticeRead:input_type -> community.NoticeIDReq
	3,  // 10: community.CommunityRpc.AdminListNotices:input_type -> community.ListNoticesReq
	8,  // 11: community.CommunityRpc.CreateNotice:input_type -> community.CreateNoticeReq
	5,  // 12: community.CommunityRpc.DeleteNotice:input_type -> community.NoticeIDReq
	5,  // 13: community.CommunityRpc.GetNoticeViews:input_type -> community.NoticeIDReq
	10, // 14: community.CommunityRpc.CreateVisitor:input_type -> community.CreateVisitorReq
	11, // 15: community.CommunityRpc.ListMyVisitors:input_type -> community.ListVisitorReq
	11, // 16: community.CommunityRpc.AdminListVisitors:input_type -> community.ListVisitorReq
	13, // 17: community.CommunityRpc.AuditVisitor:input_type -> community.AuditVisitorReq
	1,  // 18: community.CommunityRpc.ListMyParking:input_type -> community.UserIDReq
	15, // 19: community.CommunityRpc.BindPlate:input_type -> community.BindPlateReq
	16, // 20: community.CommunityRpc.AdminListParking:input_type -> community.ListParkingReq
	18, // 21: community.CommunityRpc.CreateParking:input_type -> community.CreateParkingReq
	19, // 22: community.CommunityRpc.AssignParking:input_type -> community.AssignParkingReq
	0,  // 23: community.CommunityRpc.GetParkingStats:input_type -> community.BaseResp
	22, // 24: community.CommunityRpc.ListMyFees:input_type -> community.ListPropertyFeesReq
	25, // 25: community.CommunityRpc.PayPropertyFee:input_type -> community.PayPropertyFeeReq
	27, // 26: community.CommunityRpc.ListMyPayments:input_type -> community.ListPaymentsReq
	22, // 27: community.CommunityRpc.AdminListFees:input_type -> community.ListPropertyFeesReq
	24, // 28: community.CommunityRpc.AdminCreateFee:input_type -> community.CreatePropertyFeeReq
	27, // 29: community.CommunityRpc.AdminListPayments:input_type -> community.ListPaymentsReq
	30, // 30: community.CommunityRpc.ListMessages:input_type -> community.ListMessagesReq
	32, // 31: community.CommunityRpc.SendMessage:input_type -> community.SendMessageReq
	4,  // 32: community.CommunityRpc.ListNotices:output_type -> community.NoticeListResp
	6,  // 33: community.CommunityRpc.GetNoticeDetail:output_type -> community.NoticeDetailResp
	0,  // 34: community.CommunityRpc.MarkNoticeRead:output_type -> community.BaseResp
	4,  // 35: community.CommunityRpc.AdminListNotices:output_type -> community.NoticeListResp
	0,  // 36: community.CommunityRpc.CreateNotice:output_type -> community.BaseResp
	0,  // 37: community.CommunityRpc.DeleteNotice:output_type -> community.BaseResp
	7,  // 38: community.CommunityRpc.GetNoticeViews:output_type -> community.NoticeViewsResp
	0,  // 39: community.CommunityRpc.CreateVisitor:output_type -> community.BaseResp
	12, // 40: community.CommunityRpc.ListMyVisitors:output_type -> community.VisitorListResp
	12, // 41: community.CommunityRpc.AdminListVisitors:output_type -> community.VisitorListResp
	0,  // 42: community.CommunityRpc.AuditVisitor:output_type -> community.BaseResp
	17, // 43: community.CommunityRpc.ListMyParking:output_type -> community.ParkingListResp
	0,  // 44: community.CommunityRpc.BindPlate:output_type -> community.BaseResp
	17, // 45: community.CommunityRpc.AdminListParking:output_type -> community.ParkingListResp
	0,  // 46: community.CommunityRpc.CreateParking:output_type -> community.BaseResp
	0,  // 47: community.CommunityRpc.AssignParking:output_type -> community.BaseResp
	20, // 48: community.CommunityRpc.GetParkingStats:output_type -> community.ParkingStatsResp
	23, // 49: community.CommunityRpc.ListMyFees:output_type -> community.PropertyFeeListResp
	0,  // 50: community.CommunityRpc.PayPropertyFee:output_type -> community.BaseResp
	28, // 51: community.CommunityRpc.ListMyPayments:output_type -> community.PaymentListResp
	23, // 52: community.CommunityRpc.AdminListFees:output_type -> community.PropertyFeeListResp
	0,  // 53: community.CommunityRpc.AdminCreateFee:output_type -> community.BaseResp
	28, // 54: community.CommunityRpc.AdminListPayments:output_type -> community.PaymentListResp
	31, // 55: community.CommunityRpc.ListMessages:output_type -> community.MessageListResp
	0,  // 56: community.CommunityRpc.SendMessage:output_type -> community.BaseResp
	32, // [32:57] is the sub-list for method output_type
	7,  // [7:32] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_app_community_rpc_community_proto_init() }
func file_app_community_rpc_community_proto_init() {
	if File_app_community_rpc_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_community_rpc_community_proto_rawDesc), len(file_app_community_rpc_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_community_rpc_community_proto_goTypes,
		DependencyIndexes: file_app_community_rpc_community_proto_depIdxs,
		MessageInfos:      file_app_community_rpc_community_proto_msgTypes,
	}.Build()
	File_app_community_rpc_community_proto = out.File
	file_app_community_rpc_community_proto_goTypes = nil
	file_app_community_rpc_community_proto_depIdxs = nil
}
