apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-service
  namespace: smart-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-service
  template:
    metadata:
      labels:
        app: mall-service
    spec:
      containers:
        - name: mall-service
          image: smartcommunity/mall-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: mall-service
  namespace: smart-community
spec:
  selector:
    app: mall-service
  ports:
    - port: 8002
      targetPort: 8002
