// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"smartcommunity-microservices/app/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login-code",
				Handler: LoginCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password-reset",
				Handler: ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password-reset/code",
				Handler: ResetPasswordCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sms-code",
				Handler: SmsCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/users"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/green-points/leaderboard",
				Handler: GetGreenPointsLeaderboardHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/green-points/upload-garbage",
				Handler: UploadGarbageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/me",
				Handler: GetMeHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/me",
				Handler: UpdateMeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/me/face",
				Handler: RegisterMeFaceHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/me/password",
				Handler: ChangeMePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: MallCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: MallCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: MallProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products/:id",
				Handler: MallProductDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stores",
				Handler: MallStoresHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/mall"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cart/items",
				Handler: MallAddCartItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cart/items",
				Handler: MallCartListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/cart/items/:id",
				Handler: MallDeleteCartItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/cart/items/:id",
				Handler: MallUpdateCartItemQtyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comments",
				Handler: MallCreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/favorites",
				Handler: MallAddFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/favorites",
				Handler: MallFavoriteListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/favorites/:productId",
				Handler: MallDeleteFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/favorites/check/:productId",
				Handler: MallCheckFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: MallCreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: MallOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/:id",
				Handler: MallOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/:id/cancel",
				Handler: MallCancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/:id/pay",
				Handler: MallPayOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/:id/receive",
				Handler: MallReceiveOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/available-stores",
				Handler: MallAvailableStoresHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wallet/balance",
				Handler: MallWalletBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallet/recharge",
				Handler: MallRechargeWalletHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wallet/transactions",
				Handler: MallWalletTransactionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallet/transfer",
				Handler: MallTransferWalletHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/mall"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: AdminMallOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/:id/ship",
				Handler: AdminMallShipOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: AdminMallProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/products",
				Handler: AdminMallCreateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/products/:id",
				Handler: AdminMallUpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/products/:id",
				Handler: AdminMallDeleteProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/store-products",
				Handler: AdminMallBindStoreProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/store-products",
				Handler: AdminMallUnbindStoreProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/store-products/:storeId",
				Handler: AdminMallStoreProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/store-products/status",
				Handler: AdminMallUpdateStoreProductStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/store-products/stock",
				Handler: AdminMallUpdateStoreProductStockHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stores",
				Handler: AdminMallListStoresHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/stores",
				Handler: AdminMallCreateStoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/stores/:id",
				Handler: AdminMallUpdateStoreHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/stores/:id",
				Handler: AdminMallDeleteStoreHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/mall"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/notices",
				Handler: CommunityNoticesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notices/:id",
				Handler: CommunityNoticeDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: CommunityPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/community"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/message",
				Handler: CommunitySendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/messages",
				Handler: CommunityMessagesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notices/:id/read",
				Handler: CommunityMarkNoticeReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/parking-spaces/:id/plate",
				Handler: CommunityBindPlateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/parking-spaces/my",
				Handler: CommunityMyParkingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/property-fees",
				Handler: CommunityMyFeesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/property-fees/:id/pay",
				Handler: CommunityPayFeeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/property-fees/payments",
				Handler: CommunityMyPaymentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/visitors",
				Handler: CommunityCreateVisitorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/visitors",
				Handler: CommunityMyVisitorsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/community"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/notices",
				Handler: AdminCommunityNoticesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notices",
				Handler: AdminCommunityCreateNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notices/:id",
				Handler: AdminCommunityDeleteNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notices/:id/views",
				Handler: AdminCommunityNoticeViewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/parking-spaces",
				Handler: AdminCommunityParkingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/parking-spaces",
				Handler: AdminCommunityCreateParkingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/parking-spaces/:id/assign",
				Handler: AdminCommunityAssignParkingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/parking-spaces/statistics",
				Handler: AdminCommunityParkingStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/property-fees",
				Handler: AdminCommunityFeesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/property-fees",
				Handler: AdminCommunityCreateFeeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/property-fees/payments",
				Handler: AdminCommunityPaymentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/visitors",
				Handler: AdminCommunityVisitorsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/visitors/:id/audit",
				Handler: AdminCommunityAuditVisitorHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/community"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: WorkorderPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/workorders"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: WorkorderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: WorkorderMyListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id/logs",
				Handler: WorkorderLogsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/workorders"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: AdminWorkorderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id/process",
				Handler: AdminWorkorderProcessHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/workorders"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ai-report/:id",
				Handler: StatsReportDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ai-report/generate",
				Handler: StatsGenerateReportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ai-report/latest",
				Handler: StatsLatestReportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ai-report/list",
				Handler: StatsListReportsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/community/overview",
				Handler: StatsCommunityOverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: StatsOrdersCombinedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products/sales-rank",
				Handler: StatsProductSalesRankHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products/view-rank",
				Handler: StatsProductViewRankHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workorders",
				Handler: StatsWorkordersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/statistics"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/payments/alipay/notify",
				Handler: MallAlipayNotifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/mall"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat/stream",
				Handler: ChatStreamHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations",
				Handler: ListConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/conversations",
				Handler: CreateConversationHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/conversations/:id",
				Handler: DeleteConversationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations/:id/history",
				Handler: GetChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sessions/:id/actions/:actionId/approve",
				Handler: ApproveActionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sessions/:id/actions/:actionId/reject",
				Handler: RejectActionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/agent"),
	)
}
