// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: app/stats/rpc/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsRpc_GetProductSalesRank_FullMethodName   = "/stats.StatsRpc/GetProductSalesRank"
	StatsRpc_GetProductViewRank_FullMethodName    = "/stats.StatsRpc/GetProductViewRank"
	StatsRpc_GetCommunityOverview_FullMethodName  = "/stats.StatsRpc/GetCommunityOverview"
	StatsRpc_GetOrderStatsCombined_FullMethodName = "/stats.StatsRpc/GetOrderStatsCombined"
	StatsRpc_GetWorkorderStats_FullMethodName     = "/stats.StatsRpc/GetWorkorderStats"
	StatsRpc_GenerateAIReport_FullMethodName      = "/stats.StatsRpc/GenerateAIReport"
	StatsRpc_GetLatestAIReport_FullMethodName     = "/stats.StatsRpc/GetLatestAIReport"
	StatsRpc_ListAIReports_FullMethodName         = "/stats.StatsRpc/ListAIReports"
	StatsRpc_GetAIReportDetail_FullMethodName     = "/stats.StatsRpc/GetAIReportDetail"
)

// StatsRpcClient is the client API for StatsRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsRpcClient interface {
	GetProductSalesRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*SalesRankResp, error)
	GetProductViewRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*ViewRankResp, error)
	GetCommunityOverview(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*CommunityOverviewResp, error)
	GetOrderStatsCombined(ctx context.Context, in *DaysReq, opts ...grpc.CallOption) (*OrderStatsResp, error)
	GetWorkorderStats(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*WorkorderStatsResp, error)
	GenerateAIReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*ReportResp, error)
	GetLatestAIReport(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*ReportResp, error)
	ListAIReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ReportListResp, error)
	GetAIReportDetail(ctx context.Context, in *ReportIDReq, opts ...grpc.CallOption) (*ReportResp, error)
}

type statsRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsRpcClient(cc grpc.ClientConnInterface) StatsRpcClient {
	return &statsRpcClient{cc}
}

func (c *statsRpcClient) GetProductSalesRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*SalesRankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalesRankResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetProductSalesRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GetProductViewRank(ctx context.Context, in *RankLimitReq, opts ...grpc.CallOption) (*ViewRankResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewRankResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetProductViewRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GetCommunityOverview(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*CommunityOverviewResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommunityOverviewResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetCommunityOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GetOrderStatsCombined(ctx context.Context, in *DaysReq, opts ...grpc.CallOption) (*OrderStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatsResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetOrderStatsCombined_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GetWorkorderStats(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*WorkorderStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkorderStatsResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetWorkorderStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GenerateAIReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*ReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResp)
	err := c.cc.Invoke(ctx, StatsRpc_GenerateAIReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GetLatestAIReport(ctx context.Context, in *BaseResp, opts ...grpc.CallOption) (*ReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetLatestAIReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) ListAIReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ReportListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportListResp)
	err := c.cc.Invoke(ctx, StatsRpc_ListAIReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsRpcClient) GetAIReportDetail(ctx context.Context, in *ReportIDReq, opts ...grpc.CallOption) (*ReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResp)
	err := c.cc.Invoke(ctx, StatsRpc_GetAIReportDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsRpcServer is the server API for StatsRpc service.
// All implementations must embed UnimplementedStatsRpcServer
// for forward compatibility.
type StatsRpcServer interface {
	GetProductSalesRank(context.Context, *RankLimitReq) (*SalesRankResp, error)
	GetProductViewRank(context.Context, *RankLimitReq) (*ViewRankResp, error)
	GetCommunityOverview(context.Context, *BaseResp) (*CommunityOverviewResp, error)
	GetOrderStatsCombined(context.Context, *DaysReq) (*OrderStatsResp, error)
	GetWorkorderStats(context.Context, *BaseResp) (*WorkorderStatsResp, error)
	GenerateAIReport(context.Context, *GenerateReportReq) (*ReportResp, error)
	GetLatestAIReport(context.Context, *BaseResp) (*ReportResp, error)
	ListAIReports(context.Context, *ListReportsReq) (*ReportListResp, error)
	GetAIReportDetail(context.Context, *ReportIDReq) (*ReportResp, error)
	mustEmbedUnimplementedStatsRpcServer()
}

// UnimplementedStatsRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsRpcServer struct{}

func (UnimplementedStatsRpcServer) GetProductSalesRank(context.Context, *RankLimitReq) (*SalesRankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductSalesRank not implemented")
}
func (UnimplementedStatsRpcServer) GetProductViewRank(context.Context, *RankLimitReq) (*ViewRankResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductViewRank not implemented")
}
func (UnimplementedStatsRpcServer) GetCommunityOverview(context.Context, *BaseResp) (*CommunityOverviewResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommunityOverview not implemented")
}
func (UnimplementedStatsRpcServer) GetOrderStatsCombined(context.Context, *DaysReq) (*OrderStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderStatsCombined not implemented")
}
func (UnimplementedStatsRpcServer) GetWorkorderStats(context.Context, *BaseResp) (*WorkorderStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkorderStats not implemented")
}
func (UnimplementedStatsRpcServer) GenerateAIReport(context.Context, *GenerateReportReq) (*ReportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAIReport not implemented")
}
func (UnimplementedStatsRpcServer) GetLatestAIReport(context.Context, *BaseResp) (*ReportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestAIReport not implemented")
}
func (UnimplementedStatsRpcServer) ListAIReports(context.Context, *ListReportsReq) (*ReportListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAIReports not implemented")
}
func (UnimplementedStatsRpcServer) GetAIReportDetail(context.Context, *ReportIDReq) (*ReportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAIReportDetail not implemented")
}
func (UnimplementedStatsRpcServer) mustEmbedUnimplementedStatsRpcServer() {}
func (UnimplementedStatsRpcServer) testEmbeddedByValue()                  {}

// UnsafeStatsRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsRpcServer will
// result in compilation errors.
type UnsafeStatsRpcServer interface {
	mustEmbedUnimplementedStatsRpcServer()
}

func RegisterStatsRpcServer(s grpc.ServiceRegistrar, srv StatsRpcServer) {
	// If the following call panics, it indicates UnimplementedStatsRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsRpc_ServiceDesc, srv)
}

func _StatsRpc_GetProductSalesRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetProductSalesRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetProductSalesRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetProductSalesRank(ctx, req.(*RankLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GetProductViewRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetProductViewRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetProductViewRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetProductViewRank(ctx, req.(*RankLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GetCommunityOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetCommunityOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetCommunityOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetCommunityOverview(ctx, req.(*BaseResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GetOrderStatsCombined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetOrderStatsCombined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetOrderStatsCombined_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetOrderStatsCombined(ctx, req.(*DaysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GetWorkorderStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetWorkorderStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetWorkorderStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetWorkorderStats(ctx, req.(*BaseResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GenerateAIReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GenerateAIReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GenerateAIReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GenerateAIReport(ctx, req.(*GenerateReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GetLatestAIReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseResp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetLatestAIReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetLatestAIReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetLatestAIReport(ctx, req.(*BaseResp))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_ListAIReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).ListAIReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_ListAIReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).ListAIReports(ctx, req.(*ListReportsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsRpc_GetAIReportDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsRpcServer).GetAIReportDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsRpc_GetAIReportDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsRpcServer).GetAIReportDetail(ctx, req.(*ReportIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsRpc_ServiceDesc is the grpc.ServiceDesc for StatsRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsRpc",
	HandlerType: (*StatsRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductSalesRank",
			Handler:    _StatsRpc_GetProductSalesRank_Handler,
		},
		{
			MethodName: "GetProductViewRank",
			Handler:    _StatsRpc_GetProductViewRank_Handler,
		},
		{
			MethodName: "GetCommunityOverview",
			Handler:    _StatsRpc_GetCommunityOverview_Handler,
		},
		{
			MethodName: "GetOrderStatsCombined",
			Handler:    _StatsRpc_GetOrderStatsCombined_Handler,
		},
		{
			MethodName: "GetWorkorderStats",
			Handler:    _StatsRpc_GetWorkorderStats_Handler,
		},
		{
			MethodName: "GenerateAIReport",
			Handler:    _StatsRpc_GenerateAIReport_Handler,
		},
		{
			MethodName: "GetLatestAIReport",
			Handler:    _StatsRpc_GetLatestAIReport_Handler,
		},
		{
			MethodName: "ListAIReports",
			Handler:    _StatsRpc_ListAIReports_Handler,
		},
		{
			MethodName: "GetAIReportDetail",
			Handler:    _StatsRpc_GetAIReportDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/stats/rpc/stats.proto",
}
