// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: app/stats/rpc/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SalesRankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	TotalSales    int64                  `protobuf:"varint,3,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesRankInfo) Reset() {
	*x = SalesRankInfo{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesRankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesRankInfo) ProtoMessage() {}

func (x *SalesRankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesRankInfo.ProtoReflect.Descriptor instead.
func (*SalesRankInfo) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{1}
}

func (x *SalesRankInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SalesRankInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SalesRankInfo) GetTotalSales() int64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *SalesRankInfo) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type SalesRankResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SalesRankInfo       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesRankResp) Reset() {
	*x = SalesRankResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesRankResp) ProtoMessage() {}

func (x *SalesRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesRankResp.ProtoReflect.Descriptor instead.
func (*SalesRankResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{2}
}

func (x *SalesRankResp) GetList() []*SalesRankInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ViewRankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ViewCount     int64                  `protobuf:"varint,3,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	UniqueUsers   int64                  `protobuf:"varint,4,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewRankInfo) Reset() {
	*x = ViewRankInfo{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRankInfo) ProtoMessage() {}

func (x *ViewRankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRankInfo.ProtoReflect.Descriptor instead.
func (*ViewRankInfo) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{3}
}

func (x *ViewRankInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ViewRankInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ViewRankInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ViewRankInfo) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

type ViewRankResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ViewRankInfo        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewRankResp) Reset() {
	*x = ViewRankResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRankResp) ProtoMessage() {}

func (x *ViewRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRankResp.ProtoReflect.Descriptor instead.
func (*ViewRankResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{4}
}

func (x *ViewRankResp) GetList() []*ViewRankInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type CommunityOverviewResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserCount      int64                  `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	OrderCount     int64                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	PaidAmount     float64                `protobuf:"fixed64,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	RepairCount    int64                  `protobuf:"varint,4,opt,name=repair_count,json=repairCount,proto3" json:"repair_count,omitempty"`
	ComplaintCount int64                  `protobuf:"varint,5,opt,name=complaint_count,json=complaintCount,proto3" json:"complaint_count,omitempty"`
	FeeCount       int64                  `protobuf:"varint,6,opt,name=fee_count,json=feeCount,proto3" json:"fee_count,omitempty"`
	FeePaidCount   int64                  `protobuf:"varint,7,opt,name=fee_paid_count,json=feePaidCount,proto3" json:"fee_paid_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommunityOverviewResp) Reset() {
	*x = CommunityOverviewResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityOverviewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityOverviewResp) ProtoMessage() {}

func (x *CommunityOverviewResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityOverviewResp.ProtoReflect.Descriptor instead.
func (*CommunityOverviewResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{5}
}

func (x *CommunityOverviewResp) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *CommunityOverviewResp) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *CommunityOverviewResp) GetPaidAmount() float64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *CommunityOverviewResp) GetRepairCount() int64 {
	if x != nil {
		return x.RepairCount
	}
	return 0
}

func (x *CommunityOverviewResp) GetComplaintCount() int64 {
	if x != nil {
		return x.ComplaintCount
	}
	return 0
}

func (x *CommunityOverviewResp) GetFeeCount() int64 {
	if x != nil {
		return x.FeeCount
	}
	return 0
}

func (x *CommunityOverviewResp) GetFeePaidCount() int64 {
	if x != nil {
		return x.FeePaidCount
	}
	return 0
}

type OrderSummaryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderSummaryInfo) Reset() {
	*x = OrderSummaryInfo{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSummaryInfo) ProtoMessage() {}

func (x *OrderSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSummaryInfo.ProtoReflect.Descriptor instead.
func (*OrderSummaryInfo) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{6}
}

func (x *OrderSummaryInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderSummaryInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderSummaryInfo) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type OrderTrendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTrendInfo) Reset() {
	*x = OrderTrendInfo{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTrendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTrendInfo) ProtoMessage() {}

func (x *OrderTrendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTrendInfo.ProtoReflect.Descriptor instead.
func (*OrderTrendInfo) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{7}
}

func (x *OrderTrendInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *OrderTrendInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderTrendInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*OrderSummaryInfo    `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	Trends        []*OrderTrendInfo      `protobuf:"bytes,2,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatsResp) Reset() {
	*x = OrderStatsResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatsResp) ProtoMessage() {}

func (x *OrderStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatsResp.ProtoReflect.Descriptor instead.
func (*OrderStatsResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{8}
}

func (x *OrderStatsResp) GetSummaries() []*OrderSummaryInfo {
	if x != nil {
		return x.Summaries
	}
	return nil
}

func (x *OrderStatsResp) GetTrends() []*OrderTrendInfo {
	if x != nil {
		return x.Trends
	}
	return nil
}

type WorkorderSummaryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkorderSummaryInfo) Reset() {
	*x = WorkorderSummaryInfo{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkorderSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkorderSummaryInfo) ProtoMessage() {}

func (x *WorkorderSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkorderSummaryInfo.ProtoReflect.Descriptor instead.
func (*WorkorderSummaryInfo) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{9}
}

func (x *WorkorderSummaryInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkorderSummaryInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WorkorderSummaryInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type WorkorderStatsResp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Summaries     []*WorkorderSummaryInfo `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkorderStatsResp) Reset() {
	*x = WorkorderStatsResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkorderStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkorderStatsResp) ProtoMessage() {}

func (x *WorkorderStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkorderStatsResp.ProtoReflect.Descriptor instead.
func (*WorkorderStatsResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{10}
}

func (x *WorkorderStatsResp) GetSummaries() []*WorkorderSummaryInfo {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type GenerateReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportReq) Reset() {
	*x = GenerateReportReq{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportReq) ProtoMessage() {}

func (x *GenerateReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportReq.ProtoReflect.Descriptor instead.
func (*GenerateReportReq) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateReportReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AIReportInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RepairNewCount     int64                  `protobuf:"varint,2,opt,name=repair_new_count,json=repairNewCount,proto3" json:"repair_new_count,omitempty"`
	RepairPendingCount int64                  `protobuf:"varint,3,opt,name=repair_pending_count,json=repairPendingCount,proto3" json:"repair_pending_count,omitempty"`
	VisitorNewCount    int64                  `protobuf:"varint,4,opt,name=visitor_new_count,json=visitorNewCount,proto3" json:"visitor_new_count,omitempty"`
	PropertyPaidCount  int64                  `protobuf:"varint,5,opt,name=property_paid_count,json=propertyPaidCount,proto3" json:"property_paid_count,omitempty"`
	PropertyPaidAmount float64                `protobuf:"fixed64,6,opt,name=property_paid_amount,json=propertyPaidAmount,proto3" json:"property_paid_amount,omitempty"`
	ReportSummary      string                 `protobuf:"bytes,7,opt,name=report_summary,json=reportSummary,proto3" json:"report_summary,omitempty"`
	ReportMarkdown     string                 `protobuf:"bytes,8,opt,name=report_markdown,json=reportMarkdown,proto3" json:"report_markdown,omitempty"`
	GeneratedBy        int64                  `protobuf:"varint,9,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AIReportInfo) Reset() {
	*x = AIReportInfo{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIReportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIReportInfo) ProtoMessage() {}

func (x *AIReportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIReportInfo.ProtoReflect.Descriptor instead.
func (*AIReportInfo) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{12}
}

func (x *AIReportInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AIReportInfo) GetRepairNewCount() int64 {
	if x != nil {
		return x.RepairNewCount
	}
	return 0
}

func (x *AIReportInfo) GetRepairPendingCount() int64 {
	if x != nil {
		return x.RepairPendingCount
	}
	return 0
}

func (x *AIReportInfo) GetVisitorNewCount() int64 {
	if x != nil {
		return x.VisitorNewCount
	}
	return 0
}

func (x *AIReportInfo) GetPropertyPaidCount() int64 {
	if x != nil {
		return x.PropertyPaidCount
	}
	return 0
}

func (x *AIReportInfo) GetPropertyPaidAmount() float64 {
	if x != nil {
		return x.PropertyPaidAmount
	}
	return 0
}

func (x *AIReportInfo) GetReportSummary() string {
	if x != nil {
		return x.ReportSummary
	}
	return ""
}

func (x *AIReportInfo) GetReportMarkdown() string {
	if x != nil {
		return x.ReportMarkdown
	}
	return ""
}

func (x *AIReportInfo) GetGeneratedBy() int64 {
	if x != nil {
		return x.GeneratedBy
	}
	return 0
}

func (x *AIReportInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ReportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *AIReportInfo          `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResp) Reset() {
	*x = ReportResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResp) ProtoMessage() {}

func (x *ReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResp.ProtoReflect.Descriptor instead.
func (*ReportResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{13}
}

func (x *ReportResp) GetReport() *AIReportInfo {
	if x != nil {
		return x.Report
	}
	return nil
}

type ListReportsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsReq) Reset() {
	*x = ListReportsReq{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsReq) ProtoMessage() {}

func (x *ListReportsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsReq.ProtoReflect.Descriptor instead.
func (*ListReportsReq) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{14}
}

func (x *ListReportsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReportsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReportListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AIReportInfo        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportListResp) Reset() {
	*x = ReportListResp{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportListResp) ProtoMessage() {}

func (x *ReportListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportListResp.ProtoReflect.Descriptor instead.
func (*ReportListResp) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{15}
}

func (x *ReportListResp) GetList() []*AIReportInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ReportListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReportIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportIDReq) Reset() {
	*x = ReportIDReq{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportIDReq) ProtoMessage() {}

func (x *ReportIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportIDReq.ProtoReflect.Descriptor instead.
func (*ReportIDReq) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{16}
}

func (x *ReportIDReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RankLimitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankLimitReq) Reset() {
	*x = RankLimitReq{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankLimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankLimitReq) ProtoMessage() {}

func (x *RankLimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankLimitReq.ProtoReflect.Descriptor instead.
func (*RankLimitReq) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{17}
}

func (x *RankLimitReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DaysReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaysReq) Reset() {
	*x = DaysReq{}
	mi := &file_app_stats_rpc_stats_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaysReq) ProtoMessage() {}

func (x *DaysReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_stats_rpc_stats_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaysReq.ProtoReflect.Descriptor instead.
func (*DaysReq) Descriptor() ([]byte, []int) {
	return file_app_stats_rpc_stats_proto_rawDescGZIP(), []int{18}
}

func (x *DaysReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

var File_app_stats_rpc_stats_proto protoreflect.FileDescriptor

const file_app_stats_rpc_stats_proto_rawDesc = "" +
	"\n" +
	"\x19app/stats/rpc/stats.proto\x12\x05stats\"8\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x01\n" +
	"\rSalesRankInfo\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1f\n" +
	"\vtotal_sales\x18\x03 \x01(\x03R\n" +
	"totalSales\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\"9\n" +
	"\rSalesRankResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.stats.SalesRankInfoR\x04list\"\x92\x01\n" +
	"\fViewRankInfo\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"view_count\x18\x03 \x01(\x03R\tviewCount\x12!\n" +
	"\funique_users\x18\x04 \x01(\x03R\vuniqueUsers\"7\n" +
	"\fViewRankResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.stats.ViewRankInfoR\x04list\"\x87\x02\n" +
	"\x15CommunityOverviewResp\x12\x1d\n" +
	"\n" +
	"user_count\x18\x01 \x01(\x03R\tuserCount\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x03R\n" +
	"orderCount\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\x01R\n" +
	"paidAmount\x12!\n" +
	"\frepair_count\x18\x04 \x01(\x03R\vrepairCount\x12'\n" +
	"\x0fcomplaint_count\x18\x05 \x01(\x03R\x0ecomplaintCount\x12\x1b\n" +
	"\tfee_count\x18\x06 \x01(\x03R\bfeeCount\x12$\n" +
	"\x0efee_paid_count\x18\a \x01(\x03R\ffeePaidCount\"c\n" +
	"\x10OrderSummaryInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\"R\n" +
	"\x0eOrderTrendInfo\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"v\n" +
	"\x0eOrderStatsResp\x125\n" +
	"\tsummaries\x18\x01 \x03(\v2\x17.stats.OrderSummaryInfoR\tsummaries\x12-\n" +
	"\x06trends\x18\x02 \x03(\v2\x15.stats.OrderTrendInfoR\x06trends\"X\n" +
	"\x14WorkorderSummaryInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"O\n" +
	"\x12WorkorderStatsResp\x129\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1b.stats.WorkorderSummaryInfoR\tsummaries\",\n" +
	"\x11GenerateReportReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x9a\x03\n" +
	"\fAIReportInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\x10repair_new_count\x18\x02 \x01(\x03R\x0erepairNewCount\x120\n" +
	"\x14repair_pending_count\x18\x03 \x01(\x03R\x12repairPendingCount\x12*\n" +
	"\x11visitor_new_count\x18\x04 \x01(\x03R\x0fvisitorNewCount\x12.\n" +
	"\x13property_paid_count\x18\x05 \x01(\x03R\x11propertyPaidCount\x120\n" +
	"\x14property_paid_amount\x18\x06 \x01(\x01R\x12propertyPaidAmount\x12%\n" +
	"\x0ereport_summary\x18\a \x01(\tR\rreportSummary\x12'\n" +
	"\x0freport_markdown\x18\b \x01(\tR\x0ereportMarkdown\x12!\n" +
	"\fgenerated_by\x18\t \x01(\x03R\vgeneratedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"9\n" +
	"\n" +
	"ReportResp\x12+\n" +
	"\x06report\x18\x01 \x01(\v2\x13.stats.AIReportInfoR\x06report\"8\n" +
	"\x0eListReportsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"O\n" +
	"\x0eReportListResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.stats.AIReportInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1d\n" +
	"\vReportIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\fRankLimitReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x1d\n" +
	"\aDaysReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days2\xc9\x04\n" +
	"\bStatsRpc\x12@\n" +
	"\x13GetProductSalesRank\x12\x13.stats.RankLimitReq\x1a\x14.stats.SalesRankResp\x12>\n" +
	"\x12GetProductViewRank\x12\x13.stats.RankLimitReq\x1a\x13.stats.ViewRankResp\x12E\n" +
	"\x14GetCommunityOverview\x12\x0f.stats.BaseResp\x1a\x1c.stats.CommunityOverviewResp\x12>\n" +
	"\x15GetOrderStatsCombined\x12\x0e.stats.DaysReq\x1a\x15.stats.OrderStatsResp\x12?\n" +
	"\x11GetWorkorderStats\x12\x0f.stats.BaseResp\x1a\x19.stats.WorkorderStatsResp\x12?\n" +
	"\x10GenerateAIReport\x12\x18.stats.GenerateReportReq\x1a\x11.stats.ReportResp\x127\n" +
	"\x11GetLatestAIReport\x12\x0f.stats.BaseResp\x1a\x11.stats.ReportResp\x12=\n" +
	"\rListAIReports\x12\x15.stats.ListReportsReq\x1a\x15.stats.ReportListResp\x12:\n" +
	"\x11GetAIReportDetail\x12\x12.stats.ReportIDReq\x1a\x11.stats.ReportRespB\tZ\a./statsb\x06proto3"

var (
	file_app_stats_rpc_stats_proto_rawDescOnce sync.Once
	file_app_stats_rpc_stats_proto_rawDescData []byte
)

func file_app_stats_rpc_stats_proto_rawDescGZIP() []byte {
	file_app_stats_rpc_stats_proto_rawDescOnce.Do(func() {
		file_app_stats_rpc_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_stats_rpc_stats_proto_rawDesc), len(file_app_stats_rpc_stats_proto_rawDesc)))
	})
	return file_app_stats_rpc_stats_proto_rawDescData
}

var file_app_stats_rpc_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_app_stats_rpc_stats_proto_goTypes = []any{
	(*BaseResp)(nil),              // 0: stats.BaseResp
	(*SalesRankInfo)(nil),         // 1: stats.SalesRankInfo
	(*SalesRankResp)(nil),         // 2: stats.SalesRankResp
	(*ViewRankInfo)(nil),          // 3: stats.ViewRankInfo
	(*ViewRankResp)(nil),          // 4: stats.ViewRankResp
	(*CommunityOverviewResp)(nil), // 5: stats.CommunityOverviewResp
	(*OrderSummaryInfo)(nil),      // 6: stats.OrderSummaryInfo
	(*OrderTrendInfo)(nil),        // 7: stats.OrderTrendInfo
	(*OrderStatsResp)(nil),        // 8: stats.OrderStatsResp
	(*WorkorderSummaryInfo)(nil),  // 9: stats.WorkorderSummaryInfo
	(*WorkorderStatsResp)(nil),    // 10: stats.WorkorderStatsResp
	(*GenerateReportReq)(nil),     // 11: stats.GenerateReportReq
	(*AIReportInfo)(nil),          // 12: stats.AIReportInfo
	(*ReportResp)(nil),            // 13: stats.ReportResp
	(*ListReportsReq)(nil),        // 14: stats.ListReportsReq
	(*ReportListResp)(nil),        // 15: stats.ReportListResp
	(*ReportIDReq)(nil),           // 16: stats.ReportIDReq
	(*RankLimitReq)(nil),          // 17: stats.RankLimitReq
	(*DaysReq)(nil),               // 18: stats.DaysReq
}
var file_app_stats_rpc_stats_proto_depIdxs = []int32{
	1,  // 0: stats.SalesRankResp.list:type_name -> stats.SalesRankInfo
	3,  // 1: stats.ViewRankResp.list:type_name -> stats.ViewRankInfo
	6,  // 2: stats.OrderStatsResp.summaries:type_name -> stats.OrderSummaryInfo
	7,  // 3: stats.OrderStatsResp.trends:type_name -> stats.OrderTrendInfo
	9,  // 4: stats.WorkorderStatsResp.summaries:type_name -> stats.WorkorderSummaryInfo
	12, // 5: stats.ReportResp.report:type_name -> stats.AIReportInfo
	12, // 6: stats.ReportListResp.list:type_name -> stats.AIReportInfo
	17, // 7: stats.StatsRpc.GetProductSalesRank:input_type -> stats.RankLimitReq
	17, // 8: stats.StatsRpc.GetProductViewRank:input_type -> stats.RankLimitReq
	0,  // 9: stats.StatsRpc.GetCommunityOverview:input_type -> stats.BaseResp
	18, // 10: stats.StatsRpc.GetOrderStatsCombined:input_type -> stats.DaysReq
	0,  // 11: stats.StatsRpc.GetWorkorderStats:input_type -> stats.BaseResp
	11, // 12: stats.StatsRpc.GenerateAIReport:input_type -> stats.GenerateReportReq
	0,  // 13: stats.StatsRpc.GetLatestAIReport:input_type -> stats.BaseResp
	14, // 14: stats.StatsRpc.ListAIReports:input_type -> stats.ListReportsReq
	16, // 15: stats.StatsRpc.GetAIReportDetail:input_type -> stats.ReportIDReq
	2,  // 16: stats.StatsRpc.GetProductSalesRank:output_type -> stats.SalesRankResp
	4,  // 17: stats.StatsRpc.GetProductViewRank:output_type -> stats.ViewRankResp
	5,  // 18: stats.StatsRpc.GetCommunityOverview:output_type -> stats.CommunityOverviewResp
	8,  // 19: stats.StatsRpc.GetOrderStatsCombined:output_type -> stats.OrderStatsResp
	10, // 20: stats.StatsRpc.GetWorkorderStats:output_type -> stats.WorkorderStatsResp
	13, // 21: stats.StatsRpc.GenerateAIReport:output_type -> stats.ReportResp
	13, // 22: stats.StatsRpc.GetLatestAIReport:output_type -> stats.ReportResp
	15, // 23: stats.StatsRpc.ListAIReports:output_type -> stats.ReportListResp
	13, // 24: stats.StatsRpc.GetAIReportDetail:output_type -> stats.ReportResp
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_app_stats_rpc_stats_proto_init() }
func file_app_stats_rpc_stats_proto_init() {
	if File_app_stats_rpc_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_stats_rpc_stats_proto_rawDesc), len(file_app_stats_rpc_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_stats_rpc_stats_proto_goTypes,
		DependencyIndexes: file_app_stats_rpc_stats_proto_depIdxs,
		MessageInfos:      file_app_stats_rpc_stats_proto_msgTypes,
	}.Build()
	File_app_stats_rpc_stats_proto = out.File
	file_app_stats_rpc_stats_proto_goTypes = nil
	file_app_stats_rpc_stats_proto_depIdxs = nil
}
