// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type UserIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDReq) Reset() {
	*x = UserIDReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDReq) ProtoMessage() {}

func (x *UserIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDReq.ProtoReflect.Descriptor instead.
func (*UserIDReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserIDReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LoginReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginByCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByCodeReq) Reset() {
	*x = LoginByCodeReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByCodeReq) ProtoMessage() {}

func (x *LoginByCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByCodeReq.ProtoReflect.Descriptor instead.
func (*LoginByCodeReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *LoginByCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginByCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginByCodeReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LoginByCodeReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo         *UserInfo              `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	IsNewUser        bool                   `protobuf:"varint,3,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	ProfileCompleted bool                   `protobuf:"varint,4,opt,name=profile_completed,json=profileCompleted,proto3" json:"profile_completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *LoginResp) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *LoginResp) GetProfileCompleted() bool {
	if x != nil {
		return x.ProfileCompleted
	}
	return false
}

type UserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RealName       string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Mobile         string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Avatar         string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GreenPoints    int32                  `protobuf:"varint,6,opt,name=green_points,json=greenPoints,proto3" json:"green_points,omitempty"`
	Role           string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	FaceRegistered bool                   `protobuf:"varint,9,opt,name=face_registered,json=faceRegistered,proto3" json:"face_registered,omitempty"`
	FaceImageUrl   string                 `protobuf:"bytes,10,opt,name=face_image_url,json=faceImageUrl,proto3" json:"face_image_url,omitempty"`
	Balance        float64                `protobuf:"fixed64,11,opt,name=balance,proto3" json:"balance,omitempty"`
	RoleName       string                 `protobuf:"bytes,12,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Gender         int32                  `protobuf:"varint,13,opt,name=gender,proto3" json:"gender,omitempty"`
	Email          string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	Age            int32                  `protobuf:"varint,15,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetGreenPoints() int32 {
	if x != nil {
		return x.GreenPoints
	}
	return 0
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetFaceRegistered() bool {
	if x != nil {
		return x.FaceRegistered
	}
	return false
}

func (x *UserInfo) GetFaceImageUrl() string {
	if x != nil {
		return x.FaceImageUrl
	}
	return ""
}

func (x *UserInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type SendCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeReq) Reset() {
	*x = SendCodeReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeReq) ProtoMessage() {}

func (x *SendCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeReq.ProtoReflect.Descriptor instead.
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *SendCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type ResetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPasswordReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ResetPasswordReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResetPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePasswordReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Avatar        *string                `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Mobile        *string                `protobuf:"bytes,3,opt,name=mobile,proto3,oneof" json:"mobile,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Gender        *int32                 `protobuf:"varint,5,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Email         *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	RealName      *string                `protobuf:"bytes,7,opt,name=real_name,json=realName,proto3,oneof" json:"real_name,omitempty"`
	Age           *int32                 `protobuf:"varint,8,opt,name=age,proto3,oneof" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateProfileReq) GetMobile() string {
	if x != nil && x.Mobile != nil {
		return *x.Mobile
	}
	return ""
}

func (x *UpdateProfileReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateProfileReq) GetGender() int32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UpdateProfileReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateProfileReq) GetRealName() string {
	if x != nil && x.RealName != nil {
		return *x.RealName
	}
	return ""
}

func (x *UpdateProfileReq) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

type RegisterFaceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FaceImageUrl  string                 `protobuf:"bytes,2,opt,name=face_image_url,json=faceImageUrl,proto3" json:"face_image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFaceReq) Reset() {
	*x = RegisterFaceReq{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFaceReq) ProtoMessage() {}

func (x *RegisterFaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFaceReq.ProtoReflect.Descriptor instead.
func (*RegisterFaceReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterFaceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterFaceReq) GetFaceImageUrl() string {
	if x != nil {
		return x.FaceImageUrl
	}
	return ""
}

type CheckTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenReq) Reset() {
	*x = CheckTokenReq{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenReq) ProtoMessage() {}

func (x *CheckTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenReq.ProtoReflect.Descriptor instead.
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *CheckTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResp) Reset() {
	*x = CheckTokenResp{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResp) ProtoMessage() {}

func (x *CheckTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResp.ProtoReflect.Descriptor instead.
func (*CheckTokenResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *CheckTokenResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckTokenResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type PermissionListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionListResp) Reset() {
	*x = PermissionListResp{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionListResp) ProtoMessage() {}

func (x *PermissionListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionListResp.ProtoReflect.Descriptor instead.
func (*PermissionListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *PermissionListResp) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type RoleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResp) Reset() {
	*x = RoleListResp{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResp) ProtoMessage() {}

func (x *RoleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResp.ProtoReflect.Descriptor instead.
func (*RoleListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *RoleListResp) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DeleteRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReq) Reset() {
	*x = DeleteRoleReq{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReq) ProtoMessage() {}

func (x *DeleteRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReq.ProtoReflect.Descriptor instead.
func (*DeleteRoleReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BindRoleMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MenuIds       []int64                `protobuf:"varint,2,rep,packed,name=menu_ids,json=menuIds,proto3" json:"menu_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRoleMenuReq) Reset() {
	*x = BindRoleMenuReq{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRoleMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRoleMenuReq) ProtoMessage() {}

func (x *BindRoleMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRoleMenuReq.ProtoReflect.Descriptor instead.
func (*BindRoleMenuReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *BindRoleMenuReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BindRoleMenuReq) GetMenuIds() []int64 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

type BindRolePermissionsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoleId          int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionCodes []string               `protobuf:"bytes,2,rep,name=permission_codes,json=permissionCodes,proto3" json:"permission_codes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BindRolePermissionsReq) Reset() {
	*x = BindRolePermissionsReq{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRolePermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRolePermissionsReq) ProtoMessage() {}

func (x *BindRolePermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRolePermissionsReq.ProtoReflect.Descriptor instead.
func (*BindRolePermissionsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *BindRolePermissionsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BindRolePermissionsReq) GetPermissionCodes() []string {
	if x != nil {
		return x.PermissionCodes
	}
	return nil
}

type GetRolePermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsReq) Reset() {
	*x = GetRolePermissionsReq{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsReq) ProtoMessage() {}

func (x *GetRolePermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsReq.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetRolePermissionsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ListAdminUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersReq) Reset() {
	*x = ListAdminUsersReq{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersReq) ProtoMessage() {}

func (x *ListAdminUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersReq.ProtoReflect.Descriptor instead.
func (*ListAdminUsersReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *ListAdminUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminUsersReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListAdminUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersResp) Reset() {
	*x = ListAdminUsersResp{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersResp) ProtoMessage() {}

func (x *ListAdminUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersResp.ProtoReflect.Descriptor instead.
func (*ListAdminUsersResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *ListAdminUsersResp) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAdminUsersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FreezeUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeUserReq) Reset() {
	*x = FreezeUserReq{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeUserReq) ProtoMessage() {}

func (x *FreezeUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeUserReq.ProtoReflect.Descriptor instead.
func (*FreezeUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *FreezeUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FreezeUserReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AssignRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleReq) Reset() {
	*x = AssignRoleReq{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleReq) ProtoMessage() {}

func (x *AssignRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleReq.ProtoReflect.Descriptor instead.
func (*AssignRoleReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *AssignRoleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UpdateUserBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserBalanceReq) Reset() {
	*x = UpdateUserBalanceReq{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserBalanceReq) ProtoMessage() {}

func (x *UpdateUserBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserBalanceReq.ProtoReflect.Descriptor instead.
func (*UpdateUserBalanceReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateUserBalanceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserBalanceReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AssignUserRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserRolesReq) Reset() {
	*x = AssignUserRolesReq{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserRolesReq) ProtoMessage() {}

func (x *AssignUserRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserRolesReq.ProtoReflect.Descriptor instead.
func (*AssignUserRolesReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *AssignUserRolesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignUserRolesReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type GetUserRolesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleIds       []int64                `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResp) Reset() {
	*x = GetUserRolesResp{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResp) ProtoMessage() {}

func (x *GetUserRolesResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResp.ProtoReflect.Descriptor instead.
func (*GetUserRolesResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserRolesResp) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type ListMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersReq) Reset() {
	*x = ListMembersReq{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersReq) ProtoMessage() {}

func (x *ListMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersReq.ProtoReflect.Descriptor instead.
func (*ListMembersReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *ListMembersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembersReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResp) Reset() {
	*x = ListMembersResp{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResp) ProtoMessage() {}

func (x *ListMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResp.ProtoReflect.Descriptor instead.
func (*ListMembersResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *ListMembersResp) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListMembersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Type          int32                  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Menu) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Menu) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ListMenusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Menu                `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenusResp) Reset() {
	*x = ListMenusResp{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenusResp) ProtoMessage() {}

func (x *ListMenusResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenusResp.ProtoReflect.Descriptor instead.
func (*ListMenusResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *ListMenusResp) GetList() []*Menu {
	if x != nil {
		return x.List
	}
	return nil
}

type LoginLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLog) Reset() {
	*x = LoginLog{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLog) ProtoMessage() {}

func (x *LoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLog.ProtoReflect.Descriptor instead.
func (*LoginLog) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

func (x *LoginLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginLog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LoginLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type QueryLoginLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLoginLogsReq) Reset() {
	*x = QueryLoginLogsReq{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLoginLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLoginLogsReq) ProtoMessage() {}

func (x *QueryLoginLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLoginLogsReq.ProtoReflect.Descriptor instead.
func (*QueryLoginLogsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *QueryLoginLogsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryLoginLogsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QueryLoginLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LoginLog            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLoginLogsResp) Reset() {
	*x = QueryLoginLogsResp{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLoginLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLoginLogsResp) ProtoMessage() {}

func (x *QueryLoginLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLoginLogsResp.ProtoReflect.Descriptor instead.
func (*QueryLoginLogsResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

func (x *QueryLoginLogsResp) GetList() []*LoginLog {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *QueryLoginLogsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateUserPointsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Points        int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPointsReq) Reset() {
	*x = UpdateUserPointsReq{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPointsReq) ProtoMessage() {}

func (x *UpdateUserPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPointsReq.ProtoReflect.Descriptor instead.
func (*UpdateUserPointsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

func (x *UpdateUserPointsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserPointsReq) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type VerifyPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordReq) Reset() {
	*x = VerifyPasswordReq{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordReq) ProtoMessage() {}

func (x *VerifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordReq.ProtoReflect.Descriptor instead.
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *VerifyPasswordReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResp) Reset() {
	*x = VerifyPasswordResp{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResp) ProtoMessage() {}

func (x *VerifyPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResp.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *VerifyPasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"8\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\n" +
	"\n" +
	"\bEmptyReq\"$\n" +
	"\tUserIDReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\vRegisterReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"'\n" +
	"\fRegisterResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"z\n" +
	"\bLoginReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"x\n" +
	"\x0eLoginByCodeReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"\x9b\x01\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12+\n" +
	"\tuser_info\x18\x02 \x01(\v2\x0e.user.UserInfoR\buserInfo\x12\x1e\n" +
	"\vis_new_user\x18\x03 \x01(\bR\tisNewUser\x12+\n" +
	"\x11profile_completed\x18\x04 \x01(\bR\x10profileCompleted\"\x98\x03\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12!\n" +
	"\fgreen_points\x18\x06 \x01(\x05R\vgreenPoints\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12'\n" +
	"\x0fface_registered\x18\t \x01(\bR\x0efaceRegistered\x12$\n" +
	"\x0eface_image_url\x18\n" +
	" \x01(\tR\ffaceImageUrl\x12\x18\n" +
	"\abalance\x18\v \x01(\x01R\abalance\x12\x1b\n" +
	"\trole_name\x18\f \x01(\tR\broleName\x12\x16\n" +
	"\x06gender\x18\r \x01(\x05R\x06gender\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x0f \x01(\x05R\x03age\"%\n" +
	"\vSendCodeReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"a\n" +
	"\x10ResetPasswordReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"r\n" +
	"\x11ChangePasswordReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\xc5\x02\n" +
	"\x10UpdateProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\x06avatar\x18\x02 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06mobile\x18\x03 \x01(\tH\x01R\x06mobile\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x05 \x01(\x05H\x03R\x06gender\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x04R\x05email\x88\x01\x01\x12 \n" +
	"\treal_name\x18\a \x01(\tH\x05R\brealName\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\b \x01(\x05H\x06R\x03age\x88\x01\x01B\t\n" +
	"\a_avatarB\t\n" +
	"\a_mobileB\v\n" +
	"\t_usernameB\t\n" +
	"\a_genderB\b\n" +
	"\x06_emailB\f\n" +
	"\n" +
	"_real_nameB\x06\n" +
	"\x04_age\"P\n" +
	"\x0fRegisterFaceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x0eface_image_url\x18\x02 \x01(\tR\ffaceImageUrl\"%\n" +
	"\rCheckTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"=\n" +
	"\x0eCheckTokenResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"6\n" +
	"\x12PermissionListResp\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"V\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"0\n" +
	"\fRoleListResp\x12 \n" +
	"\x05roles\x18\x01 \x03(\v2\n" +
	".user.RoleR\x05roles\"O\n" +
	"\rCreateRoleReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"_\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\x1f\n" +
	"\rDeleteRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x0fBindRoleMenuReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x19\n" +
	"\bmenu_ids\x18\x02 \x03(\x03R\amenuIds\"\\\n" +
	"\x16BindRolePermissionsReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12)\n" +
	"\x10permission_codes\x18\x02 \x03(\tR\x0fpermissionCodes\"0\n" +
	"\x15GetRolePermissionsReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\";\n" +
	"\x11ListAdminUsersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"N\n" +
	"\x12ListAdminUsersResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"@\n" +
	"\rFreezeUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"A\n" +
	"\rAssignRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"G\n" +
	"\x14UpdateUserBalanceReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"H\n" +
	"\x12AssignUserRolesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x03R\aroleIds\"-\n" +
	"\x10GetUserRolesResp\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\x03R\aroleIds\"8\n" +
	"\x0eListMembersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"K\n" +
	"\x0fListMembersResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa1\x01\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12\x12\n" +
	"\x04type\x18\a \x01(\x05R\x04type\"/\n" +
	"\rListMenusResp\x12\x1e\n" +
	"\x04list\x18\x01 \x03(\v2\n" +
	".user.MenuR\x04list\"\xcf\x01\n" +
	"\bLoginLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\";\n" +
	"\x11QueryLoginLogsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"N\n" +
	"\x12QueryLoginLogsResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.LoginLogR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"F\n" +
	"\x13UpdateUserPointsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\"H\n" +
	"\x11VerifyPasswordReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\".\n" +
	"\x12VerifyPasswordResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xef\x0e\n" +
	"\aUserRpc\x121\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x124\n" +
	"\vLoginByCode\x12\x14.user.LoginByCodeReq\x1a\x0f.user.LoginResp\x122\n" +
	"\rSendLoginCode\x12\x11.user.SendCodeReq\x1a\x0e.user.BaseResp\x122\n" +
	"\rSendResetCode\x12\x11.user.SendCodeReq\x1a\x0e.user.BaseResp\x127\n" +
	"\rResetPassword\x12\x16.user.ResetPasswordReq\x1a\x0e.user.BaseResp\x12)\n" +
	"\x06Logout\x12\x0f.user.UserIDReq\x1a\x0e.user.BaseResp\x129\n" +
	"\x0eChangePassword\x12\x17.user.ChangePasswordReq\x1a\x0e.user.BaseResp\x127\n" +
	"\n" +
	"CheckToken\x12\x13.user.CheckTokenReq\x1a\x14.user.CheckTokenResp\x12-\n" +
	"\n" +
	"GetProfile\x12\x0f.user.UserIDReq\x1a\x0e.user.UserInfo\x127\n" +
	"\rUpdateProfile\x12\x16.user.UpdateProfileReq\x1a\x0e.user.BaseResp\x125\n" +
	"\fRegisterFace\x12\x15.user.RegisterFaceReq\x1a\x0e.user.BaseResp\x12-\n" +
	"\n" +
	"CreateRole\x12\x13.user.CreateRoleReq\x1a\n" +
	".user.Role\x121\n" +
	"\n" +
	"UpdateRole\x12\x13.user.UpdateRoleReq\x1a\x0e.user.BaseResp\x121\n" +
	"\n" +
	"DeleteRole\x12\x13.user.DeleteRoleReq\x1a\x0e.user.BaseResp\x12/\n" +
	"\tListRoles\x12\x0e.user.EmptyReq\x1a\x12.user.RoleListResp\x125\n" +
	"\fBindRoleMenu\x12\x15.user.BindRoleMenuReq\x1a\x0e.user.BaseResp\x12C\n" +
	"\x13BindRolePermissions\x12\x1c.user.BindRolePermissionsReq\x1a\x0e.user.BaseResp\x12K\n" +
	"\x12GetRolePermissions\x12\x1b.user.GetRolePermissionsReq\x1a\x18.user.PermissionListResp\x12?\n" +
	"\x12GetUserPermissions\x12\x0f.user.UserIDReq\x1a\x18.user.PermissionListResp\x12;\n" +
	"\x0fAssignUserRoles\x12\x18.user.AssignUserRolesReq\x1a\x0e.user.BaseResp\x127\n" +
	"\fGetUserRoles\x12\x0f.user.UserIDReq\x1a\x16.user.GetUserRolesResp\x12C\n" +
	"\x0eListAdminUsers\x12\x17.user.ListAdminUsersReq\x1a\x18.user.ListAdminUsersResp\x121\n" +
	"\n" +
	"FreezeUser\x12\x13.user.FreezeUserReq\x1a\x0e.user.BaseResp\x121\n" +
	"\n" +
	"AssignRole\x12\x13.user.AssignRoleReq\x1a\x0e.user.BaseResp\x12?\n" +
	"\x11UpdateUserBalance\x12\x1a.user.UpdateUserBalanceReq\x1a\x0e.user.BaseResp\x12:\n" +
	"\vListMembers\x12\x14.user.ListMembersReq\x1a\x15.user.ListMembersResp\x12;\n" +
	"\x0fListPermissions\x12\x0e.user.EmptyReq\x1a\x18.user.PermissionListResp\x120\n" +
	"\tListMenus\x12\x0e.user.EmptyReq\x1a\x13.user.ListMenusResp\x12G\n" +
	"\x12QueryUserLoginLogs\x12\x17.user.QueryLoginLogsReq\x1a\x18.user.QueryLoginLogsResp\x12H\n" +
	"\x13QueryAdminLoginLogs\x12\x17.user.QueryLoginLogsReq\x1a\x18.user.QueryLoginLogsResp\x12=\n" +
	"\x10UpdateUserPoints\x12\x19.user.UpdateUserPointsReq\x1a\x0e.user.BaseResp\x12C\n" +
	"\x0eVerifyPassword\x12\x17.user.VerifyPasswordReq\x1a\x18.user.VerifyPasswordRespB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_user_proto_goTypes = []any{
	(*BaseResp)(nil),               // 0: user.BaseResp
	(*EmptyReq)(nil),               // 1: user.EmptyReq
	(*UserIDReq)(nil),              // 2: user.UserIDReq
	(*RegisterReq)(nil),            // 3: user.RegisterReq
	(*RegisterResp)(nil),           // 4: user.RegisterResp
	(*LoginReq)(nil),               // 5: user.LoginReq
	(*LoginByCodeReq)(nil),         // 6: user.LoginByCodeReq
	(*LoginResp)(nil),              // 7: user.LoginResp
	(*UserInfo)(nil),               // 8: user.UserInfo
	(*SendCodeReq)(nil),            // 9: user.SendCodeReq
	(*ResetPasswordReq)(nil),       // 10: user.ResetPasswordReq
	(*ChangePasswordReq)(nil),      // 11: user.ChangePasswordReq
	(*UpdateProfileReq)(nil),       // 12: user.UpdateProfileReq
	(*RegisterFaceReq)(nil),        // 13: user.RegisterFaceReq
	(*CheckTokenReq)(nil),          // 14: user.CheckTokenReq
	(*CheckTokenResp)(nil),         // 15: user.CheckTokenResp
	(*PermissionListResp)(nil),     // 16: user.PermissionListResp
	(*Role)(nil),                   // 17: user.Role
	(*RoleListResp)(nil),           // 18: user.RoleListResp
	(*CreateRoleReq)(nil),          // 19: user.CreateRoleReq
	(*UpdateRoleReq)(nil),          // 20: user.UpdateRoleReq
	(*DeleteRoleReq)(nil),          // 21: user.DeleteRoleReq
	(*BindRoleMenuReq)(nil),        // 22: user.BindRoleMenuReq
	(*BindRolePermissionsReq)(nil), // 23: user.BindRolePermissionsReq
	(*GetRolePermissionsReq)(nil),  // 24: user.GetRolePermissionsReq
	(*ListAdminUsersReq)(nil),      // 25: user.ListAdminUsersReq
	(*ListAdminUsersResp)(nil),     // 26: user.ListAdminUsersResp
	(*FreezeUserReq)(nil),          // 27: user.FreezeUserReq
	(*AssignRoleReq)(nil),          // 28: user.AssignRoleReq
	(*UpdateUserBalanceReq)(nil),   // 29: user.UpdateUserBalanceReq
	(*AssignUserRolesReq)(nil),     // 30: user.AssignUserRolesReq
	(*GetUserRolesResp)(nil),       // 31: user.GetUserRolesResp
	(*ListMembersReq)(nil),         // 32: user.ListMembersReq
	(*ListMembersResp)(nil),        // 33: user.ListMembersResp
	(*Menu)(nil),                   // 34: user.Menu
	(*ListMenusResp)(nil),          // 35: user.ListMenusResp
	(*LoginLog)(nil),               // 36: user.LoginLog
	(*QueryLoginLogsReq)(nil),      // 37: user.QueryLoginLogsReq
	(*QueryLoginLogsResp)(nil),     // 38: user.QueryLoginLogsResp
	(*UpdateUserPointsReq)(nil),    // 39: user.UpdateUserPointsReq
	(*VerifyPasswordReq)(nil),      // 40: user.VerifyPasswordReq
	(*VerifyPasswordResp)(nil),     // 41: user.VerifyPasswordResp
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: user.LoginResp.user_info:type_name -> user.UserInfo
	17, // 1: user.RoleListResp.roles:type_name -> user.Role
	8,  // 2: user.ListAdminUsersResp.list:type_name -> user.UserInfo
	8,  // 3: user.ListMembersResp.list:type_name -> user.UserInfo
	34, // 4: user.ListMenusResp.list:type_name -> user.Menu
	36, // 5: user.QueryLoginLogsResp.list:type_name -> user.LoginLog
	3,  // 6: user.UserRpc.Register:input_type -> user.RegisterReq
	5,  // 7: user.UserRpc.Login:input_type -> user.LoginReq
	6,  // 8: user.UserRpc.LoginByCode:input_type -> user.LoginByCodeReq
	9,  // 9: user.UserRpc.SendLoginCode:input_type -> user.SendCodeReq
	9,  // 10: user.UserRpc.SendResetCode:input_type -> user.SendCodeReq
	10, // 11: user.UserRpc.ResetPassword:input_type -> user.ResetPasswordReq
	2,  // 12: user.UserRpc.Logout:input_type -> user.UserIDReq
	11, // 13: user.UserRpc.ChangePassword:input_type -> user.ChangePasswordReq
	14, // 14: user.UserRpc.CheckToken:input_type -> user.CheckTokenReq
	2,  // 15: user.UserRpc.GetProfile:input_type -> user.UserIDReq
	12, // 16: user.UserRpc.UpdateProfile:input_type -> user.UpdateProfileReq
	13, // 17: user.UserRpc.RegisterFace:input_type -> user.RegisterFaceReq
	19, // 18: user.UserRpc.CreateRole:input_type -> user.CreateRoleReq
	20, // 19: user.UserRpc.UpdateRole:input_type -> user.UpdateRoleReq
	21, // 20: user.UserRpc.DeleteRole:input_type -> user.DeleteRoleReq
	1,  // 21: user.UserRpc.ListRoles:input_type -> user.EmptyReq
	22, // 22: user.UserRpc.BindRoleMenu:input_type -> user.BindRoleMenuReq
	23, // 23: user.UserRpc.BindRolePermissions:input_type -> user.BindRolePermissionsReq
	24, // 24: user.UserRpc.GetRolePermissions:input_type -> user.GetRolePermissionsReq
	2,  // 25: user.UserRpc.GetUserPermissions:input_type -> user.UserIDReq
	30, // 26: user.UserRpc.AssignUserRoles:input_type -> user.AssignUserRolesReq
	2,  // 27: user.UserRpc.GetUserRoles:input_type -> user.UserIDReq
	25, // 28: user.UserRpc.ListAdminUsers:input_type -> user.ListAdminUsersReq
	27, // 29: user.UserRpc.FreezeUser:input_type -> user.FreezeUserReq
	28, // 30: user.UserRpc.AssignRole:input_type -> user.AssignRoleReq
	29, // 31: user.UserRpc.UpdateUserBalance:input_type -> user.UpdateUserBalanceReq
	32, // 32: user.UserRpc.ListMembers:input_type -> user.ListMembersReq
	1,  // 33: user.UserRpc.ListPermissions:input_type -> user.EmptyReq
	1,  // 34: user.UserRpc.ListMenus:input_type -> user.EmptyReq
	37, // 35: user.UserRpc.QueryUserLoginLogs:input_type -> user.QueryLoginLogsReq
	37, // 36: user.UserRpc.QueryAdminLoginLogs:input_type -> user.QueryLoginLogsReq
	39, // 37: user.UserRpc.UpdateUserPoints:input_type -> user.UpdateUserPointsReq
	40, // 38: user.UserRpc.VerifyPassword:input_type -> user.VerifyPasswordReq
	4,  // 39: user.UserRpc.Register:output_type -> user.RegisterResp
	7,  // 40: user.UserRpc.Login:output_type -> user.LoginResp
	7,  // 41: user.UserRpc.LoginByCode:output_type -> user.LoginResp
	0,  // 42: user.UserRpc.SendLoginCode:output_type -> user.BaseResp
	0,  // 43: user.UserRpc.SendResetCode:output_type -> user.BaseResp
	0,  // 44: user.UserRpc.ResetPassword:output_type -> user.BaseResp
	0,  // 45: user.UserRpc.Logout:output_type -> user.BaseResp
	0,  // 46: user.UserRpc.ChangePassword:output_type -> user.BaseResp
	15, // 47: user.UserRpc.CheckToken:output_type -> user.CheckTokenResp
	8,  // 48: user.UserRpc.GetProfile:output_type -> user.UserInfo
	0,  // 49: user.UserRpc.UpdateProfile:output_type -> user.BaseResp
	0,  // 50: user.UserRpc.RegisterFace:output_type -> user.BaseResp
	17, // 51: user.UserRpc.CreateRole:output_type -> user.Role
	0,  // 52: user.UserRpc.UpdateRole:output_type -> user.BaseResp
	0,  // 53: user.UserRpc.DeleteRole:output_type -> user.BaseResp
	18, // 54: user.UserRpc.ListRoles:output_type -> user.RoleListResp
	0,  // 55: user.UserRpc.BindRoleMenu:output_type -> user.BaseResp
	0,  // 56: user.UserRpc.BindRolePermissions:output_type -> user.BaseResp
	16, // 57: user.UserRpc.GetRolePermissions:output_type -> user.PermissionListResp
	16, // 58: user.UserRpc.GetUserPermissions:output_type -> user.PermissionListResp
	0,  // 59: user.UserRpc.AssignUserRoles:output_type -> user.BaseResp
	31, // 60: user.UserRpc.GetUserRoles:output_type -> user.GetUserRolesResp
	26, // 61: user.UserRpc.ListAdminUsers:output_type -> user.ListAdminUsersResp
	0,  // 62: user.UserRpc.FreezeUser:output_type -> user.BaseResp
	0,  // 63: user.UserRpc.AssignRole:output_type -> user.BaseResp
	0,  // 64: user.UserRpc.UpdateUserBalance:output_type -> user.BaseResp
	33, // 65: user.UserRpc.ListMembers:output_type -> user.ListMembersResp
	16, // 66: user.UserRpc.ListPermissions:output_type -> user.PermissionListResp
	35, // 67: user.UserRpc.ListMenus:output_type -> user.ListMenusResp
	38, // 68: user.UserRpc.QueryUserLoginLogs:output_type -> user.QueryLoginLogsResp
	38, // 69: user.UserRpc.QueryAdminLoginLogs:output_type -> user.QueryLoginLogsResp
	0,  // 70: user.UserRpc.UpdateUserPoints:output_type -> user.BaseResp
	41, // 71: user.UserRpc.VerifyPassword:output_type -> user.VerifyPasswordResp
	39, // [39:72] is the sub-list for method output_type
	6,  // [6:39] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
