// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: app/user/rpc/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRpc_Register_FullMethodName            = "/user.UserRpc/Register"
	UserRpc_Login_FullMethodName               = "/user.UserRpc/Login"
	UserRpc_LoginByCode_FullMethodName         = "/user.UserRpc/LoginByCode"
	UserRpc_SendLoginCode_FullMethodName       = "/user.UserRpc/SendLoginCode"
	UserRpc_SendResetCode_FullMethodName       = "/user.UserRpc/SendResetCode"
	UserRpc_ResetPassword_FullMethodName       = "/user.UserRpc/ResetPassword"
	UserRpc_Logout_FullMethodName              = "/user.UserRpc/Logout"
	UserRpc_ChangePassword_FullMethodName      = "/user.UserRpc/ChangePassword"
	UserRpc_CheckToken_FullMethodName          = "/user.UserRpc/CheckToken"
	UserRpc_GetProfile_FullMethodName          = "/user.UserRpc/GetProfile"
	UserRpc_UpdateProfile_FullMethodName       = "/user.UserRpc/UpdateProfile"
	UserRpc_RegisterFace_FullMethodName        = "/user.UserRpc/RegisterFace"
	UserRpc_CreateRole_FullMethodName          = "/user.UserRpc/CreateRole"
	UserRpc_UpdateRole_FullMethodName          = "/user.UserRpc/UpdateRole"
	UserRpc_DeleteRole_FullMethodName          = "/user.UserRpc/DeleteRole"
	UserRpc_ListRoles_FullMethodName           = "/user.UserRpc/ListRoles"
	UserRpc_BindRoleMenu_FullMethodName        = "/user.UserRpc/BindRoleMenu"
	UserRpc_BindRolePermissions_FullMethodName = "/user.UserRpc/BindRolePermissions"
	UserRpc_GetRolePermissions_FullMethodName  = "/user.UserRpc/GetRolePermissions"
	UserRpc_GetUserPermissions_FullMethodName  = "/user.UserRpc/GetUserPermissions"
	UserRpc_AssignUserRoles_FullMethodName     = "/user.UserRpc/AssignUserRoles"
	UserRpc_GetUserRoles_FullMethodName        = "/user.UserRpc/GetUserRoles"
	UserRpc_ListAdminUsers_FullMethodName      = "/user.UserRpc/ListAdminUsers"
	UserRpc_FreezeUser_FullMethodName          = "/user.UserRpc/FreezeUser"
	UserRpc_AssignRole_FullMethodName          = "/user.UserRpc/AssignRole"
	UserRpc_UpdateUserBalance_FullMethodName   = "/user.UserRpc/UpdateUserBalance"
	UserRpc_ListMembers_FullMethodName         = "/user.UserRpc/ListMembers"
	UserRpc_ListPermissions_FullMethodName     = "/user.UserRpc/ListPermissions"
	UserRpc_ListMenus_FullMethodName           = "/user.UserRpc/ListMenus"
	UserRpc_QueryUserLoginLogs_FullMethodName  = "/user.UserRpc/QueryUserLoginLogs"
	UserRpc_QueryAdminLoginLogs_FullMethodName = "/user.UserRpc/QueryAdminLoginLogs"
	UserRpc_UpdateUserPoints_FullMethodName    = "/user.UserRpc/UpdateUserPoints"
)

// UserRpcClient is the client API for UserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRpcClient interface {
	// Authentication & Session
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	LoginByCode(ctx context.Context, in *LoginByCodeReq, opts ...grpc.CallOption) (*LoginResp, error)
	SendLoginCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*BaseResp, error)
	SendResetCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*BaseResp, error)
	ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*BaseResp, error)
	Logout(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*BaseResp, error)
	CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenResp, error)
	// Profile & Face
	GetProfile(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*UserInfo, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*BaseResp, error)
	RegisterFace(ctx context.Context, in *RegisterFaceReq, opts ...grpc.CallOption) (*BaseResp, error)
	// RBAC Roles & Permissions
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*Role, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
	DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
	ListRoles(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*RoleListResp, error)
	BindRoleMenu(ctx context.Context, in *BindRoleMenuReq, opts ...grpc.CallOption) (*BaseResp, error)
	BindRolePermissions(ctx context.Context, in *BindRolePermissionsReq, opts ...grpc.CallOption) (*BaseResp, error)
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*PermissionListResp, error)
	GetUserPermissions(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*PermissionListResp, error)
	AssignUserRoles(ctx context.Context, in *AssignUserRolesReq, opts ...grpc.CallOption) (*BaseResp, error)
	GetUserRoles(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*GetUserRolesResp, error)
	// Admin Operations
	ListAdminUsers(ctx context.Context, in *ListAdminUsersReq, opts ...grpc.CallOption) (*ListAdminUsersResp, error)
	FreezeUser(ctx context.Context, in *FreezeUserReq, opts ...grpc.CallOption) (*BaseResp, error)
	AssignRole(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateUserBalance(ctx context.Context, in *UpdateUserBalanceReq, opts ...grpc.CallOption) (*BaseResp, error)
	ListMembers(ctx context.Context, in *ListMembersReq, opts ...grpc.CallOption) (*ListMembersResp, error)
	ListPermissions(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*PermissionListResp, error)
	ListMenus(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*ListMenusResp, error)
	// Audit Logs
	QueryUserLoginLogs(ctx context.Context, in *QueryLoginLogsReq, opts ...grpc.CallOption) (*QueryLoginLogsResp, error)
	QueryAdminLoginLogs(ctx context.Context, in *QueryLoginLogsReq, opts ...grpc.CallOption) (*QueryLoginLogsResp, error)
	// Points Management
	UpdateUserPoints(ctx context.Context, in *UpdateUserPointsReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type userRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcClient(cc grpc.ClientConnInterface) UserRpcClient {
	return &userRpcClient{cc}
}

func (c *userRpcClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, UserRpc_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, UserRpc_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) LoginByCode(ctx context.Context, in *LoginByCodeReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, UserRpc_LoginByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) SendLoginCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_SendLoginCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) SendResetCode(ctx context.Context, in *SendCodeReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_SendResetCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) Logout(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTokenResp)
	err := c.cc.Invoke(ctx, UserRpc_CheckToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetProfile(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserRpc_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) RegisterFace(ctx context.Context, in *RegisterFaceReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_RegisterFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, UserRpc_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ListRoles(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleListResp)
	err := c.cc.Invoke(ctx, UserRpc_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) BindRoleMenu(ctx context.Context, in *BindRoleMenuReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_BindRoleMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) BindRolePermissions(ctx context.Context, in *BindRolePermissionsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_BindRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*PermissionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionListResp)
	err := c.cc.Invoke(ctx, UserRpc_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetUserPermissions(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*PermissionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionListResp)
	err := c.cc.Invoke(ctx, UserRpc_GetUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) AssignUserRoles(ctx context.Context, in *AssignUserRolesReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_AssignUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetUserRoles(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*GetUserRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRolesResp)
	err := c.cc.Invoke(ctx, UserRpc_GetUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersReq, opts ...grpc.CallOption) (*ListAdminUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResp)
	err := c.cc.Invoke(ctx, UserRpc_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) FreezeUser(ctx context.Context, in *FreezeUserReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_FreezeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) AssignRole(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_AssignRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) UpdateUserBalance(ctx context.Context, in *UpdateUserBalanceReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_UpdateUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ListMembers(ctx context.Context, in *ListMembersReq, opts ...grpc.CallOption) (*ListMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResp)
	err := c.cc.Invoke(ctx, UserRpc_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ListPermissions(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*PermissionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionListResp)
	err := c.cc.Invoke(ctx, UserRpc_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ListMenus(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*ListMenusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMenusResp)
	err := c.cc.Invoke(ctx, UserRpc_ListMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) QueryUserLoginLogs(ctx context.Context, in *QueryLoginLogsReq, opts ...grpc.CallOption) (*QueryLoginLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLoginLogsResp)
	err := c.cc.Invoke(ctx, UserRpc_QueryUserLoginLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) QueryAdminLoginLogs(ctx context.Context, in *QueryLoginLogsReq, opts ...grpc.CallOption) (*QueryLoginLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLoginLogsResp)
	err := c.cc.Invoke(ctx, UserRpc_QueryAdminLoginLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) UpdateUserPoints(ctx context.Context, in *UpdateUserPointsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, UserRpc_UpdateUserPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServer is the server API for UserRpc service.
// All implementations must embed UnimplementedUserRpcServer
// for forward compatibility.
type UserRpcServer interface {
	// Authentication & Session
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	LoginByCode(context.Context, *LoginByCodeReq) (*LoginResp, error)
	SendLoginCode(context.Context, *SendCodeReq) (*BaseResp, error)
	SendResetCode(context.Context, *SendCodeReq) (*BaseResp, error)
	ResetPassword(context.Context, *ResetPasswordReq) (*BaseResp, error)
	Logout(context.Context, *UserIDReq) (*BaseResp, error)
	ChangePassword(context.Context, *ChangePasswordReq) (*BaseResp, error)
	CheckToken(context.Context, *CheckTokenReq) (*CheckTokenResp, error)
	// Profile & Face
	GetProfile(context.Context, *UserIDReq) (*UserInfo, error)
	UpdateProfile(context.Context, *UpdateProfileReq) (*BaseResp, error)
	RegisterFace(context.Context, *RegisterFaceReq) (*BaseResp, error)
	// RBAC Roles & Permissions
	CreateRole(context.Context, *CreateRoleReq) (*Role, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*BaseResp, error)
	DeleteRole(context.Context, *DeleteRoleReq) (*BaseResp, error)
	ListRoles(context.Context, *EmptyReq) (*RoleListResp, error)
	BindRoleMenu(context.Context, *BindRoleMenuReq) (*BaseResp, error)
	BindRolePermissions(context.Context, *BindRolePermissionsReq) (*BaseResp, error)
	GetRolePermissions(context.Context, *GetRolePermissionsReq) (*PermissionListResp, error)
	GetUserPermissions(context.Context, *UserIDReq) (*PermissionListResp, error)
	AssignUserRoles(context.Context, *AssignUserRolesReq) (*BaseResp, error)
	GetUserRoles(context.Context, *UserIDReq) (*GetUserRolesResp, error)
	// Admin Operations
	ListAdminUsers(context.Context, *ListAdminUsersReq) (*ListAdminUsersResp, error)
	FreezeUser(context.Context, *FreezeUserReq) (*BaseResp, error)
	AssignRole(context.Context, *AssignRoleReq) (*BaseResp, error)
	UpdateUserBalance(context.Context, *UpdateUserBalanceReq) (*BaseResp, error)
	ListMembers(context.Context, *ListMembersReq) (*ListMembersResp, error)
	ListPermissions(context.Context, *EmptyReq) (*PermissionListResp, error)
	ListMenus(context.Context, *EmptyReq) (*ListMenusResp, error)
	// Audit Logs
	QueryUserLoginLogs(context.Context, *QueryLoginLogsReq) (*QueryLoginLogsResp, error)
	QueryAdminLoginLogs(context.Context, *QueryLoginLogsReq) (*QueryLoginLogsResp, error)
	// Points Management
	UpdateUserPoints(context.Context, *UpdateUserPointsReq) (*BaseResp, error)
	mustEmbedUnimplementedUserRpcServer()
}

// UnimplementedUserRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRpcServer struct{}

func (UnimplementedUserRpcServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserRpcServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserRpcServer) LoginByCode(context.Context, *LoginByCodeReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginByCode not implemented")
}
func (UnimplementedUserRpcServer) SendLoginCode(context.Context, *SendCodeReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLoginCode not implemented")
}
func (UnimplementedUserRpcServer) SendResetCode(context.Context, *SendCodeReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendResetCode not implemented")
}
func (UnimplementedUserRpcServer) ResetPassword(context.Context, *ResetPasswordReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedUserRpcServer) Logout(context.Context, *UserIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedUserRpcServer) ChangePassword(context.Context, *ChangePasswordReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserRpcServer) CheckToken(context.Context, *CheckTokenReq) (*CheckTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckToken not implemented")
}
func (UnimplementedUserRpcServer) GetProfile(context.Context, *UserIDReq) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUserRpcServer) UpdateProfile(context.Context, *UpdateProfileReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserRpcServer) RegisterFace(context.Context, *RegisterFaceReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFace not implemented")
}
func (UnimplementedUserRpcServer) CreateRole(context.Context, *CreateRoleReq) (*Role, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedUserRpcServer) UpdateRole(context.Context, *UpdateRoleReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedUserRpcServer) DeleteRole(context.Context, *DeleteRoleReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedUserRpcServer) ListRoles(context.Context, *EmptyReq) (*RoleListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedUserRpcServer) BindRoleMenu(context.Context, *BindRoleMenuReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindRoleMenu not implemented")
}
func (UnimplementedUserRpcServer) BindRolePermissions(context.Context, *BindRolePermissionsReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindRolePermissions not implemented")
}
func (UnimplementedUserRpcServer) GetRolePermissions(context.Context, *GetRolePermissionsReq) (*PermissionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedUserRpcServer) GetUserPermissions(context.Context, *UserIDReq) (*PermissionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (UnimplementedUserRpcServer) AssignUserRoles(context.Context, *AssignUserRolesReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignUserRoles not implemented")
}
func (UnimplementedUserRpcServer) GetUserRoles(context.Context, *UserIDReq) (*GetUserRolesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRoles not implemented")
}
func (UnimplementedUserRpcServer) ListAdminUsers(context.Context, *ListAdminUsersReq) (*ListAdminUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedUserRpcServer) FreezeUser(context.Context, *FreezeUserReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeUser not implemented")
}
func (UnimplementedUserRpcServer) AssignRole(context.Context, *AssignRoleReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedUserRpcServer) UpdateUserBalance(context.Context, *UpdateUserBalanceReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserBalance not implemented")
}
func (UnimplementedUserRpcServer) ListMembers(context.Context, *ListMembersReq) (*ListMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedUserRpcServer) ListPermissions(context.Context, *EmptyReq) (*PermissionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedUserRpcServer) ListMenus(context.Context, *EmptyReq) (*ListMenusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMenus not implemented")
}
func (UnimplementedUserRpcServer) QueryUserLoginLogs(context.Context, *QueryLoginLogsReq) (*QueryLoginLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUserLoginLogs not implemented")
}
func (UnimplementedUserRpcServer) QueryAdminLoginLogs(context.Context, *QueryLoginLogsReq) (*QueryLoginLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAdminLoginLogs not implemented")
}
func (UnimplementedUserRpcServer) UpdateUserPoints(context.Context, *UpdateUserPointsReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserPoints not implemented")
}
func (UnimplementedUserRpcServer) mustEmbedUnimplementedUserRpcServer() {}
func (UnimplementedUserRpcServer) testEmbeddedByValue()                 {}

// UnsafeUserRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcServer will
// result in compilation errors.
type UnsafeUserRpcServer interface {
	mustEmbedUnimplementedUserRpcServer()
}

func RegisterUserRpcServer(s grpc.ServiceRegistrar, srv UserRpcServer) {
	// If the following call panics, it indicates UnimplementedUserRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRpc_ServiceDesc, srv)
}

func _UserRpc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_LoginByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).LoginByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_LoginByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).LoginByCode(ctx, req.(*LoginByCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_SendLoginCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).SendLoginCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_SendLoginCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).SendLoginCode(ctx, req.(*SendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_SendResetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).SendResetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_SendResetCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).SendResetCode(ctx, req.(*SendCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ResetPassword(ctx, req.(*ResetPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).Logout(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ChangePassword(ctx, req.(*ChangePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_CheckToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).CheckToken(ctx, req.(*CheckTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetProfile(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).UpdateProfile(ctx, req.(*UpdateProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_RegisterFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).RegisterFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_RegisterFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).RegisterFace(ctx, req.(*RegisterFaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).DeleteRole(ctx, req.(*DeleteRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ListRoles(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_BindRoleMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRoleMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).BindRoleMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_BindRoleMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).BindRoleMenu(ctx, req.(*BindRoleMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_BindRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).BindRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_BindRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).BindRolePermissions(ctx, req.(*BindRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetRolePermissions(ctx, req.(*GetRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetUserPermissions(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_AssignUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).AssignUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_AssignUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).AssignUserRoles(ctx, req.(*AssignUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetUserRoles(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ListAdminUsers(ctx, req.(*ListAdminUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_FreezeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).FreezeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_FreezeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).FreezeUser(ctx, req.(*FreezeUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_AssignRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).AssignRole(ctx, req.(*AssignRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_UpdateUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).UpdateUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_UpdateUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).UpdateUserBalance(ctx, req.(*UpdateUserBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ListMembers(ctx, req.(*ListMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ListPermissions(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ListMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ListMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ListMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ListMenus(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_QueryUserLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLoginLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).QueryUserLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_QueryUserLoginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).QueryUserLoginLogs(ctx, req.(*QueryLoginLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_QueryAdminLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLoginLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).QueryAdminLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_QueryAdminLoginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).QueryAdminLoginLogs(ctx, req.(*QueryLoginLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_UpdateUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).UpdateUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_UpdateUserPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).UpdateUserPoints(ctx, req.(*UpdateUserPointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpc_ServiceDesc is the grpc.ServiceDesc for UserRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserRpc",
	HandlerType: (*UserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserRpc_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserRpc_Login_Handler,
		},
		{
			MethodName: "LoginByCode",
			Handler:    _UserRpc_LoginByCode_Handler,
		},
		{
			MethodName: "SendLoginCode",
			Handler:    _UserRpc_SendLoginCode_Handler,
		},
		{
			MethodName: "SendResetCode",
			Handler:    _UserRpc_SendResetCode_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserRpc_ResetPassword_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserRpc_Logout_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserRpc_ChangePassword_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _UserRpc_CheckToken_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _UserRpc_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserRpc_UpdateProfile_Handler,
		},
		{
			MethodName: "RegisterFace",
			Handler:    _UserRpc_RegisterFace_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _UserRpc_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _UserRpc_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _UserRpc_DeleteRole_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _UserRpc_ListRoles_Handler,
		},
		{
			MethodName: "BindRoleMenu",
			Handler:    _UserRpc_BindRoleMenu_Handler,
		},
		{
			MethodName: "BindRolePermissions",
			Handler:    _UserRpc_BindRolePermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _UserRpc_GetRolePermissions_Handler,
		},
		{
			MethodName: "GetUserPermissions",
			Handler:    _UserRpc_GetUserPermissions_Handler,
		},
		{
			MethodName: "AssignUserRoles",
			Handler:    _UserRpc_AssignUserRoles_Handler,
		},
		{
			MethodName: "GetUserRoles",
			Handler:    _UserRpc_GetUserRoles_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _UserRpc_ListAdminUsers_Handler,
		},
		{
			MethodName: "FreezeUser",
			Handler:    _UserRpc_FreezeUser_Handler,
		},
		{
			MethodName: "AssignRole",
			Handler:    _UserRpc_AssignRole_Handler,
		},
		{
			MethodName: "UpdateUserBalance",
			Handler:    _UserRpc_UpdateUserBalance_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _UserRpc_ListMembers_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _UserRpc_ListPermissions_Handler,
		},
		{
			MethodName: "ListMenus",
			Handler:    _UserRpc_ListMenus_Handler,
		},
		{
			MethodName: "QueryUserLoginLogs",
			Handler:    _UserRpc_QueryUserLoginLogs_Handler,
		},
		{
			MethodName: "QueryAdminLoginLogs",
			Handler:    _UserRpc_QueryAdminLoginLogs_Handler,
		},
		{
			MethodName: "UpdateUserPoints",
			Handler:    _UserRpc_UpdateUserPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/user/rpc/user.proto",
}
