// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConversationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationInfo) Reset() {
	*x = ConversationInfo{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationInfo) ProtoMessage() {}

func (x *ConversationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationInfo.ProtoReflect.Descriptor instead.
func (*ConversationInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConversationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConversationInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ConversationInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConversationInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MessageInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EventType      string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventPayload   string                 `protobuf:"bytes,6,opt,name=event_payload,json=eventPayload,proto3" json:"event_payload,omitempty"`
	ActionResolved string                 `protobuf:"bytes,7,opt,name=action_resolved,json=actionResolved,proto3" json:"action_resolved,omitempty"`
	ResultPayload  string                 `protobuf:"bytes,8,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *MessageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MessageInfo) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MessageInfo) GetEventPayload() string {
	if x != nil {
		return x.EventPayload
	}
	return ""
}

func (x *MessageInfo) GetActionResolved() string {
	if x != nil {
		return x.ActionResolved
	}
	return ""
}

func (x *MessageInfo) GetResultPayload() string {
	if x != nil {
		return x.ResultPayload
	}
	return ""
}

type CreateConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationReq) Reset() {
	*x = CreateConversationReq{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationReq) ProtoMessage() {}

func (x *CreateConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationReq.ProtoReflect.Descriptor instead.
func (*CreateConversationReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateConversationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateConversationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationReq) Reset() {
	*x = DeleteConversationReq{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationReq) ProtoMessage() {}

func (x *DeleteConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationReq.ProtoReflect.Descriptor instead.
func (*DeleteConversationReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteConversationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteConversationReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListConversationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsReq) Reset() {
	*x = ListConversationsReq{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsReq) ProtoMessage() {}

func (x *ListConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsReq.ProtoReflect.Descriptor instead.
func (*ListConversationsReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversationsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListConversationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ConversationInfo    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResp) Reset() {
	*x = ListConversationsResp{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResp) ProtoMessage() {}

func (x *ListConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResp.ProtoReflect.Descriptor instead.
func (*ListConversationsResp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsResp) GetList() []*ConversationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetChatHistoryReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChatHistoryReq) Reset() {
	*x = GetChatHistoryReq{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryReq) ProtoMessage() {}

func (x *GetChatHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryReq.ProtoReflect.Descriptor instead.
func (*GetChatHistoryReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatHistoryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatHistoryReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetChatHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MessageInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResp) Reset() {
	*x = GetChatHistoryResp{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResp) ProtoMessage() {}

func (x *GetChatHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResp.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatHistoryResp) GetList() []*MessageInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ChatReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PayType         string                 `protobuf:"bytes,4,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	PaymentPassword string                 `protobuf:"bytes,5,opt,name=payment_password,json=paymentPassword,proto3" json:"payment_password,omitempty"`
	FaceImageUrl    string                 `protobuf:"bytes,6,opt,name=face_image_url,json=faceImageUrl,proto3" json:"face_image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ChatReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatReq) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *ChatReq) GetPaymentPassword() string {
	if x != nil {
		return x.PaymentPassword
	}
	return ""
}

func (x *ChatReq) GetFaceImageUrl() string {
	if x != nil {
		return x.FaceImageUrl
	}
	return ""
}

type ChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	FullReply     string                 `protobuf:"bytes,3,opt,name=full_reply,json=fullReply,proto3" json:"full_reply,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`          // message_delta, tool_call_start, tool_call_end, approval_required, session_finished
	EventPayload  string                 `protobuf:"bytes,5,opt,name=event_payload,json=eventPayload,proto3" json:"event_payload,omitempty"` // JSON payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ChatResp) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ChatResp) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatResp) GetFullReply() string {
	if x != nil {
		return x.FullReply
	}
	return ""
}

func (x *ChatResp) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ChatResp) GetEventPayload() string {
	if x != nil {
		return x.EventPayload
	}
	return ""
}

type ApproveActionReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ActionId        string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	PaymentPassword string                 `protobuf:"bytes,4,opt,name=payment_password,json=paymentPassword,proto3" json:"payment_password,omitempty"`
	FaceImageUrl    string                 `protobuf:"bytes,5,opt,name=face_image_url,json=faceImageUrl,proto3" json:"face_image_url,omitempty"`
	PayType         string                 `protobuf:"bytes,6,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	ReturnUrl       string                 `protobuf:"bytes,7,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApproveActionReq) Reset() {
	*x = ApproveActionReq{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveActionReq) ProtoMessage() {}

func (x *ApproveActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveActionReq.ProtoReflect.Descriptor instead.
func (*ApproveActionReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveActionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApproveActionReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ApproveActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ApproveActionReq) GetPaymentPassword() string {
	if x != nil {
		return x.PaymentPassword
	}
	return ""
}

func (x *ApproveActionReq) GetFaceImageUrl() string {
	if x != nil {
		return x.FaceImageUrl
	}
	return ""
}

func (x *ApproveActionReq) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *ApproveActionReq) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type ApproveActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PayUrl        string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	OrderId       int64                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveActionResp) Reset() {
	*x = ApproveActionResp{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveActionResp) ProtoMessage() {}

func (x *ApproveActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveActionResp.ProtoReflect.Descriptor instead.
func (*ApproveActionResp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveActionResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApproveActionResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApproveActionResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *ApproveActionResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RejectActionReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ActionId       string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RejectActionReq) Reset() {
	*x = RejectActionReq{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectActionReq) ProtoMessage() {}

func (x *RejectActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectActionReq.ProtoReflect.Descriptor instead.
func (*RejectActionReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RejectActionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RejectActionReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RejectActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"8\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\x10ConversationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xfe\x01\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12#\n" +
	"\revent_payload\x18\x06 \x01(\tR\feventPayload\x12'\n" +
	"\x0faction_resolved\x18\a \x01(\tR\x0eactionResolved\x12%\n" +
	"\x0eresult_payload\x18\b \x01(\tR\rresultPayload\"F\n" +
	"\x15CreateConversationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"@\n" +
	"\x15DeleteConversationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"/\n" +
	"\x14ListConversationsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"D\n" +
	"\x15ListConversationsResp\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.agent.ConversationInfoR\x04list\"U\n" +
	"\x11GetChatHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"<\n" +
	"\x12GetChatHistoryResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.agent.MessageInfoR\x04list\"\xd1\x01\n" +
	"\aChatReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\bpay_type\x18\x04 \x01(\tR\apayType\x12)\n" +
	"\x10payment_password\x18\x05 \x01(\tR\x0fpaymentPassword\x12$\n" +
	"\x0eface_image_url\x18\x06 \x01(\tR\ffaceImageUrl\"\x97\x01\n" +
	"\bChatResp\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"full_reply\x18\x03 \x01(\tR\tfullReply\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12#\n" +
	"\revent_payload\x18\x05 \x01(\tR\feventPayload\"\xfc\x01\n" +
	"\x10ApproveActionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId\x12)\n" +
	"\x10payment_password\x18\x04 \x01(\tR\x0fpaymentPassword\x12$\n" +
	"\x0eface_image_url\x18\x05 \x01(\tR\ffaceImageUrl\x12\x19\n" +
	"\bpay_type\x18\x06 \x01(\tR\apayType\x12\x1d\n" +
	"\n" +
	"return_url\x18\a \x01(\tR\treturnUrl\"u\n" +
	"\x11ApproveActionResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x03R\aorderId\"p\n" +
	"\x0fRejectActionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId2\xe1\x03\n" +
	"\bAgentRpc\x12K\n" +
	"\x12CreateConversation\x12\x1c.agent.CreateConversationReq\x1a\x17.agent.ConversationInfo\x12C\n" +
	"\x12DeleteConversation\x12\x1c.agent.DeleteConversationReq\x1a\x0f.agent.BaseResp\x12N\n" +
	"\x11ListConversations\x12\x1b.agent.ListConversationsReq\x1a\x1c.agent.ListConversationsResp\x12E\n" +
	"\x0eGetChatHistory\x12\x18.agent.GetChatHistoryReq\x1a\x19.agent.GetChatHistoryResp\x12/\n" +
	"\n" +
	"ChatStream\x12\x0e.agent.ChatReq\x1a\x0f.agent.ChatResp0\x01\x12B\n" +
	"\rApproveAction\x12\x17.agent.ApproveActionReq\x1a\x18.agent.ApproveActionResp\x127\n" +
	"\fRejectAction\x12\x16.agent.RejectActionReq\x1a\x0f.agent.BaseRespB\tZ\a./agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_proto_goTypes = []any{
	(*BaseResp)(nil),              // 0: agent.BaseResp
	(*ConversationInfo)(nil),      // 1: agent.ConversationInfo
	(*MessageInfo)(nil),           // 2: agent.MessageInfo
	(*CreateConversationReq)(nil), // 3: agent.CreateConversationReq
	(*DeleteConversationReq)(nil), // 4: agent.DeleteConversationReq
	(*ListConversationsReq)(nil),  // 5: agent.ListConversationsReq
	(*ListConversationsResp)(nil), // 6: agent.ListConversationsResp
	(*GetChatHistoryReq)(nil),     // 7: agent.GetChatHistoryReq
	(*GetChatHistoryResp)(nil),    // 8: agent.GetChatHistoryResp
	(*ChatReq)(nil),               // 9: agent.ChatReq
	(*ChatResp)(nil),              // 10: agent.ChatResp
	(*ApproveActionReq)(nil),      // 11: agent.ApproveActionReq
	(*ApproveActionResp)(nil),     // 12: agent.ApproveActionResp
	(*RejectActionReq)(nil),       // 13: agent.RejectActionReq
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: agent.ListConversationsResp.list:type_name -> agent.ConversationInfo
	2,  // 1: agent.GetChatHistoryResp.list:type_name -> agent.MessageInfo
	3,  // 2: agent.AgentRpc.CreateConversation:input_type -> agent.CreateConversationReq
	4,  // 3: agent.AgentRpc.DeleteConversation:input_type -> agent.DeleteConversationReq
	5,  // 4: agent.AgentRpc.ListConversations:input_type -> agent.ListConversationsReq
	7,  // 5: agent.AgentRpc.GetChatHistory:input_type -> agent.GetChatHistoryReq
	9,  // 6: agent.AgentRpc.ChatStream:input_type -> agent.ChatReq
	11, // 7: agent.AgentRpc.ApproveAction:input_type -> agent.ApproveActionReq
	13, // 8: agent.AgentRpc.RejectAction:input_type -> agent.RejectActionReq
	1,  // 9: agent.AgentRpc.CreateConversation:output_type -> agent.ConversationInfo
	0,  // 10: agent.AgentRpc.DeleteConversation:output_type -> agent.BaseResp
	6,  // 11: agent.AgentRpc.ListConversations:output_type -> agent.ListConversationsResp
	8,  // 12: agent.AgentRpc.GetChatHistory:output_type -> agent.GetChatHistoryResp
	10, // 13: agent.AgentRpc.ChatStream:output_type -> agent.ChatResp
	12, // 14: agent.AgentRpc.ApproveAction:output_type -> agent.ApproveActionResp
	0,  // 15: agent.AgentRpc.RejectAction:output_type -> agent.BaseResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
