// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: app/mall/rpc/mall.proto

package mall

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MallRpc_ListProducts_FullMethodName             = "/mall.MallRpc/ListProducts"
	MallRpc_SearchProducts_FullMethodName           = "/mall.MallRpc/SearchProducts"
	MallRpc_GetProductDetail_FullMethodName         = "/mall.MallRpc/GetProductDetail"
	MallRpc_GetPromotions_FullMethodName            = "/mall.MallRpc/GetPromotions"
	MallRpc_ListStores_FullMethodName               = "/mall.MallRpc/ListStores"
	MallRpc_GetStoreDetail_FullMethodName           = "/mall.MallRpc/GetStoreDetail"
	MallRpc_ListCategories_FullMethodName           = "/mall.MallRpc/ListCategories"
	MallRpc_GetCategoryDetail_FullMethodName        = "/mall.MallRpc/GetCategoryDetail"
	MallRpc_ListServiceAreas_FullMethodName         = "/mall.MallRpc/ListServiceAreas"
	MallRpc_AddCartItem_FullMethodName              = "/mall.MallRpc/AddCartItem"
	MallRpc_RemoveCartItem_FullMethodName           = "/mall.MallRpc/RemoveCartItem"
	MallRpc_UpdateCartItemQty_FullMethodName        = "/mall.MallRpc/UpdateCartItemQty"
	MallRpc_ListCart_FullMethodName                 = "/mall.MallRpc/ListCart"
	MallRpc_AddFavorite_FullMethodName              = "/mall.MallRpc/AddFavorite"
	MallRpc_RemoveFavorite_FullMethodName           = "/mall.MallRpc/RemoveFavorite"
	MallRpc_ListFavorites_FullMethodName            = "/mall.MallRpc/ListFavorites"
	MallRpc_CheckFavorite_FullMethodName            = "/mall.MallRpc/CheckFavorite"
	MallRpc_ListComments_FullMethodName             = "/mall.MallRpc/ListComments"
	MallRpc_CreateComment_FullMethodName            = "/mall.MallRpc/CreateComment"
	MallRpc_CreateOrder_FullMethodName              = "/mall.MallRpc/CreateOrder"
	MallRpc_ListAvailableStores_FullMethodName      = "/mall.MallRpc/ListAvailableStores"
	MallRpc_PayOrder_FullMethodName                 = "/mall.MallRpc/PayOrder"
	MallRpc_CancelOrder_FullMethodName              = "/mall.MallRpc/CancelOrder"
	MallRpc_ReceiveOrder_FullMethodName             = "/mall.MallRpc/ReceiveOrder"
	MallRpc_GetOrderDetail_FullMethodName           = "/mall.MallRpc/GetOrderDetail"
	MallRpc_GetPaymentStatus_FullMethodName         = "/mall.MallRpc/GetPaymentStatus"
	MallRpc_ListOrders_FullMethodName               = "/mall.MallRpc/ListOrders"
	MallRpc_RechargeWallet_FullMethodName           = "/mall.MallRpc/RechargeWallet"
	MallRpc_TransferWallet_FullMethodName           = "/mall.MallRpc/TransferWallet"
	MallRpc_GetWalletBalance_FullMethodName         = "/mall.MallRpc/GetWalletBalance"
	MallRpc_ListWalletTransactions_FullMethodName   = "/mall.MallRpc/ListWalletTransactions"
	MallRpc_CreateCategory_FullMethodName           = "/mall.MallRpc/CreateCategory"
	MallRpc_UpdateCategory_FullMethodName           = "/mall.MallRpc/UpdateCategory"
	MallRpc_DeleteCategory_FullMethodName           = "/mall.MallRpc/DeleteCategory"
	MallRpc_AdminListProducts_FullMethodName        = "/mall.MallRpc/AdminListProducts"
	MallRpc_CreateProduct_FullMethodName            = "/mall.MallRpc/CreateProduct"
	MallRpc_UpdateProduct_FullMethodName            = "/mall.MallRpc/UpdateProduct"
	MallRpc_DeleteProduct_FullMethodName            = "/mall.MallRpc/DeleteProduct"
	MallRpc_CreateServiceArea_FullMethodName        = "/mall.MallRpc/CreateServiceArea"
	MallRpc_UpdateServiceArea_FullMethodName        = "/mall.MallRpc/UpdateServiceArea"
	MallRpc_DeleteServiceArea_FullMethodName        = "/mall.MallRpc/DeleteServiceArea"
	MallRpc_CreateStore_FullMethodName              = "/mall.MallRpc/CreateStore"
	MallRpc_UpdateStore_FullMethodName              = "/mall.MallRpc/UpdateStore"
	MallRpc_DeleteStore_FullMethodName              = "/mall.MallRpc/DeleteStore"
	MallRpc_BindStoreProduct_FullMethodName         = "/mall.MallRpc/BindStoreProduct"
	MallRpc_UnbindStoreProduct_FullMethodName       = "/mall.MallRpc/UnbindStoreProduct"
	MallRpc_UpdateStoreProductStatus_FullMethodName = "/mall.MallRpc/UpdateStoreProductStatus"
	MallRpc_UpdateStoreProductStock_FullMethodName  = "/mall.MallRpc/UpdateStoreProductStock"
	MallRpc_ListStoreProducts_FullMethodName        = "/mall.MallRpc/ListStoreProducts"
	MallRpc_AdminListOrders_FullMethodName          = "/mall.MallRpc/AdminListOrders"
	MallRpc_ShipOrder_FullMethodName                = "/mall.MallRpc/ShipOrder"
	MallRpc_AdminCancelOrder_FullMethodName         = "/mall.MallRpc/AdminCancelOrder"
	MallRpc_CancelExpiredOrder_FullMethodName       = "/mall.MallRpc/CancelExpiredOrder"
	MallRpc_DebitWallet_FullMethodName              = "/mall.MallRpc/DebitWallet"
	MallRpc_AlipayNotify_FullMethodName             = "/mall.MallRpc/AlipayNotify"
)

// MallRpcClient is the client API for MallRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MallRpcClient interface {
	ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ProductListResp, error)
	SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*ProductListResp, error)
	GetProductDetail(ctx context.Context, in *ProductIDReq, opts ...grpc.CallOption) (*ProductDetailResp, error)
	GetPromotions(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ProductListResp, error)
	ListStores(ctx context.Context, in *ListStoresReq, opts ...grpc.CallOption) (*StoreListResp, error)
	GetStoreDetail(ctx context.Context, in *StoreIDReq, opts ...grpc.CallOption) (*StoreDetailResp, error)
	ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*CategoryListResp, error)
	GetCategoryDetail(ctx context.Context, in *CategoryIDReq, opts ...grpc.CallOption) (*CategoryDetailResp, error)
	ListServiceAreas(ctx context.Context, in *ListServiceAreasReq, opts ...grpc.CallOption) (*ServiceAreaListResp, error)
	AddCartItem(ctx context.Context, in *AddCartItemReq, opts ...grpc.CallOption) (*BaseResp, error)
	RemoveCartItem(ctx context.Context, in *RemoveCartItemReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateCartItemQty(ctx context.Context, in *UpdateCartItemQtyReq, opts ...grpc.CallOption) (*BaseResp, error)
	ListCart(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*CartResp, error)
	AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...grpc.CallOption) (*BaseResp, error)
	RemoveFavorite(ctx context.Context, in *RemoveFavoriteReq, opts ...grpc.CallOption) (*BaseResp, error)
	ListFavorites(ctx context.Context, in *ListFavoritesReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
	CheckFavorite(ctx context.Context, in *CheckFavoriteReq, opts ...grpc.CallOption) (*CheckFavoriteResp, error)
	ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*CommentListResp, error)
	CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*BaseResp, error)
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*OrderInfo, error)
	ListAvailableStores(ctx context.Context, in *ListAvailableStoresReq, opts ...grpc.CallOption) (*StoreListResp, error)
	PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*BaseResp, error)
	ReceiveOrder(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	GetOrderDetail(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*OrderInfo, error)
	GetPaymentStatus(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*PaymentStatusResp, error)
	ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*OrderListResp, error)
	RechargeWallet(ctx context.Context, in *RechargeWalletReq, opts ...grpc.CallOption) (*RechargeWalletResp, error)
	TransferWallet(ctx context.Context, in *TransferWalletReq, opts ...grpc.CallOption) (*BaseResp, error)
	GetWalletBalance(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*WalletBalanceResp, error)
	ListWalletTransactions(ctx context.Context, in *ListWalletTxReq, opts ...grpc.CallOption) (*WalletTxListResp, error)
	CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*BaseResp, error)
	DeleteCategory(ctx context.Context, in *CategoryIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	AdminListProducts(ctx context.Context, in *AdminListProductsReq, opts ...grpc.CallOption) (*ProductListResp, error)
	CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*BaseResp, error)
	DeleteProduct(ctx context.Context, in *ProductIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	CreateServiceArea(ctx context.Context, in *CreateServiceAreaReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateServiceArea(ctx context.Context, in *UpdateServiceAreaReq, opts ...grpc.CallOption) (*BaseResp, error)
	DeleteServiceArea(ctx context.Context, in *CategoryIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	CreateStore(ctx context.Context, in *CreateStoreReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateStore(ctx context.Context, in *UpdateStoreReq, opts ...grpc.CallOption) (*BaseResp, error)
	DeleteStore(ctx context.Context, in *StoreIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	BindStoreProduct(ctx context.Context, in *BindStoreProductReq, opts ...grpc.CallOption) (*BaseResp, error)
	UnbindStoreProduct(ctx context.Context, in *UnbindStoreProductReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateStoreProductStatus(ctx context.Context, in *UpdateStoreProductStatusReq, opts ...grpc.CallOption) (*BaseResp, error)
	UpdateStoreProductStock(ctx context.Context, in *UpdateStoreProductStockReq, opts ...grpc.CallOption) (*BaseResp, error)
	ListStoreProducts(ctx context.Context, in *ListStoreProductsReq, opts ...grpc.CallOption) (*StoreProductListResp, error)
	AdminListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*OrderListResp, error)
	ShipOrder(ctx context.Context, in *ShipOrderReq, opts ...grpc.CallOption) (*BaseResp, error)
	AdminCancelOrder(ctx context.Context, in *AdminCancelOrderReq, opts ...grpc.CallOption) (*BaseResp, error)
	// Internal endpoints
	CancelExpiredOrder(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*BaseResp, error)
	DebitWallet(ctx context.Context, in *DebitWalletReq, opts ...grpc.CallOption) (*DebitWalletResp, error)
	AlipayNotify(ctx context.Context, in *AlipayNotifyReq, opts ...grpc.CallOption) (*AlipayNotifyResp, error)
}

type mallRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMallRpcClient(cc grpc.ClientConnInterface) MallRpcClient {
	return &mallRpcClient{cc}
}

func (c *mallRpcClient) ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResp)
	err := c.cc.Invoke(ctx, MallRpc_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetProductDetail(ctx context.Context, in *ProductIDReq, opts ...grpc.CallOption) (*ProductDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductDetailResp)
	err := c.cc.Invoke(ctx, MallRpc_GetProductDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetPromotions(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResp)
	err := c.cc.Invoke(ctx, MallRpc_GetPromotions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListStores(ctx context.Context, in *ListStoresReq, opts ...grpc.CallOption) (*StoreListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetStoreDetail(ctx context.Context, in *StoreIDReq, opts ...grpc.CallOption) (*StoreDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreDetailResp)
	err := c.cc.Invoke(ctx, MallRpc_GetStoreDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*CategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetCategoryDetail(ctx context.Context, in *CategoryIDReq, opts ...grpc.CallOption) (*CategoryDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryDetailResp)
	err := c.cc.Invoke(ctx, MallRpc_GetCategoryDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListServiceAreas(ctx context.Context, in *ListServiceAreasReq, opts ...grpc.CallOption) (*ServiceAreaListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceAreaListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListServiceAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) AddCartItem(ctx context.Context, in *AddCartItemReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_AddCartItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) RemoveCartItem(ctx context.Context, in *RemoveCartItemReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_RemoveCartItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateCartItemQty(ctx context.Context, in *UpdateCartItemQtyReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateCartItemQty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListCart(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*CartResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResp)
	err := c.cc.Invoke(ctx, MallRpc_ListCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) AddFavorite(ctx context.Context, in *AddFavoriteReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_AddFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) RemoveFavorite(ctx context.Context, in *RemoveFavoriteReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_RemoveFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListFavorites(ctx context.Context, in *ListFavoritesReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListFavorites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CheckFavorite(ctx context.Context, in *CheckFavoriteReq, opts ...grpc.CallOption) (*CheckFavoriteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFavoriteResp)
	err := c.cc.Invoke(ctx, MallRpc_CheckFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*OrderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfo)
	err := c.cc.Invoke(ctx, MallRpc_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListAvailableStores(ctx context.Context, in *ListAvailableStoresReq, opts ...grpc.CallOption) (*StoreListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListAvailableStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayOrderResp)
	err := c.cc.Invoke(ctx, MallRpc_PayOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ReceiveOrder(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_ReceiveOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetOrderDetail(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*OrderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfo)
	err := c.cc.Invoke(ctx, MallRpc_GetOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetPaymentStatus(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*PaymentStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentStatusResp)
	err := c.cc.Invoke(ctx, MallRpc_GetPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) RechargeWallet(ctx context.Context, in *RechargeWalletReq, opts ...grpc.CallOption) (*RechargeWalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RechargeWalletResp)
	err := c.cc.Invoke(ctx, MallRpc_RechargeWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) TransferWallet(ctx context.Context, in *TransferWalletReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_TransferWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) GetWalletBalance(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*WalletBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletBalanceResp)
	err := c.cc.Invoke(ctx, MallRpc_GetWalletBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListWalletTransactions(ctx context.Context, in *ListWalletTxReq, opts ...grpc.CallOption) (*WalletTxListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletTxListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListWalletTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) DeleteCategory(ctx context.Context, in *CategoryIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) AdminListProducts(ctx context.Context, in *AdminListProductsReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductListResp)
	err := c.cc.Invoke(ctx, MallRpc_AdminListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) DeleteProduct(ctx context.Context, in *ProductIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CreateServiceArea(ctx context.Context, in *CreateServiceAreaReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CreateServiceArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateServiceArea(ctx context.Context, in *UpdateServiceAreaReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateServiceArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) DeleteServiceArea(ctx context.Context, in *CategoryIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_DeleteServiceArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CreateStore(ctx context.Context, in *CreateStoreReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CreateStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateStore(ctx context.Context, in *UpdateStoreReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) DeleteStore(ctx context.Context, in *StoreIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_DeleteStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) BindStoreProduct(ctx context.Context, in *BindStoreProductReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_BindStoreProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UnbindStoreProduct(ctx context.Context, in *UnbindStoreProductReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UnbindStoreProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateStoreProductStatus(ctx context.Context, in *UpdateStoreProductStatusReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateStoreProductStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) UpdateStoreProductStock(ctx context.Context, in *UpdateStoreProductStockReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_UpdateStoreProductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ListStoreProducts(ctx context.Context, in *ListStoreProductsReq, opts ...grpc.CallOption) (*StoreProductListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreProductListResp)
	err := c.cc.Invoke(ctx, MallRpc_ListStoreProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) AdminListOrders(ctx context.Context, in *AdminListOrdersReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderListResp)
	err := c.cc.Invoke(ctx, MallRpc_AdminListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) ShipOrder(ctx context.Context, in *ShipOrderReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_ShipOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) AdminCancelOrder(ctx context.Context, in *AdminCancelOrderReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_AdminCancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) CancelExpiredOrder(ctx context.Context, in *OrderIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, MallRpc_CancelExpiredOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) DebitWallet(ctx context.Context, in *DebitWalletReq, opts ...grpc.CallOption) (*DebitWalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebitWalletResp)
	err := c.cc.Invoke(ctx, MallRpc_DebitWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallRpcClient) AlipayNotify(ctx context.Context, in *AlipayNotifyReq, opts ...grpc.CallOption) (*AlipayNotifyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlipayNotifyResp)
	err := c.cc.Invoke(ctx, MallRpc_AlipayNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MallRpcServer is the server API for MallRpc service.
// All implementations must embed UnimplementedMallRpcServer
// for forward compatibility.
type MallRpcServer interface {
	ListProducts(context.Context, *ListProductsReq) (*ProductListResp, error)
	SearchProducts(context.Context, *SearchProductsReq) (*ProductListResp, error)
	GetProductDetail(context.Context, *ProductIDReq) (*ProductDetailResp, error)
	GetPromotions(context.Context, *ListProductsReq) (*ProductListResp, error)
	ListStores(context.Context, *ListStoresReq) (*StoreListResp, error)
	GetStoreDetail(context.Context, *StoreIDReq) (*StoreDetailResp, error)
	ListCategories(context.Context, *ListCategoriesReq) (*CategoryListResp, error)
	GetCategoryDetail(context.Context, *CategoryIDReq) (*CategoryDetailResp, error)
	ListServiceAreas(context.Context, *ListServiceAreasReq) (*ServiceAreaListResp, error)
	AddCartItem(context.Context, *AddCartItemReq) (*BaseResp, error)
	RemoveCartItem(context.Context, *RemoveCartItemReq) (*BaseResp, error)
	UpdateCartItemQty(context.Context, *UpdateCartItemQtyReq) (*BaseResp, error)
	ListCart(context.Context, *UserIDReq) (*CartResp, error)
	AddFavorite(context.Context, *AddFavoriteReq) (*BaseResp, error)
	RemoveFavorite(context.Context, *RemoveFavoriteReq) (*BaseResp, error)
	ListFavorites(context.Context, *ListFavoritesReq) (*FavoriteListResp, error)
	CheckFavorite(context.Context, *CheckFavoriteReq) (*CheckFavoriteResp, error)
	ListComments(context.Context, *ListCommentsReq) (*CommentListResp, error)
	CreateComment(context.Context, *CreateCommentReq) (*BaseResp, error)
	CreateOrder(context.Context, *CreateOrderReq) (*OrderInfo, error)
	ListAvailableStores(context.Context, *ListAvailableStoresReq) (*StoreListResp, error)
	PayOrder(context.Context, *PayOrderReq) (*PayOrderResp, error)
	CancelOrder(context.Context, *CancelOrderReq) (*BaseResp, error)
	ReceiveOrder(context.Context, *OrderIDReq) (*BaseResp, error)
	GetOrderDetail(context.Context, *OrderIDReq) (*OrderInfo, error)
	GetPaymentStatus(context.Context, *OrderIDReq) (*PaymentStatusResp, error)
	ListOrders(context.Context, *ListOrdersReq) (*OrderListResp, error)
	RechargeWallet(context.Context, *RechargeWalletReq) (*RechargeWalletResp, error)
	TransferWallet(context.Context, *TransferWalletReq) (*BaseResp, error)
	GetWalletBalance(context.Context, *UserIDReq) (*WalletBalanceResp, error)
	ListWalletTransactions(context.Context, *ListWalletTxReq) (*WalletTxListResp, error)
	CreateCategory(context.Context, *CreateCategoryReq) (*BaseResp, error)
	UpdateCategory(context.Context, *UpdateCategoryReq) (*BaseResp, error)
	DeleteCategory(context.Context, *CategoryIDReq) (*BaseResp, error)
	AdminListProducts(context.Context, *AdminListProductsReq) (*ProductListResp, error)
	CreateProduct(context.Context, *CreateProductReq) (*BaseResp, error)
	UpdateProduct(context.Context, *UpdateProductReq) (*BaseResp, error)
	DeleteProduct(context.Context, *ProductIDReq) (*BaseResp, error)
	CreateServiceArea(context.Context, *CreateServiceAreaReq) (*BaseResp, error)
	UpdateServiceArea(context.Context, *UpdateServiceAreaReq) (*BaseResp, error)
	DeleteServiceArea(context.Context, *CategoryIDReq) (*BaseResp, error)
	CreateStore(context.Context, *CreateStoreReq) (*BaseResp, error)
	UpdateStore(context.Context, *UpdateStoreReq) (*BaseResp, error)
	DeleteStore(context.Context, *StoreIDReq) (*BaseResp, error)
	BindStoreProduct(context.Context, *BindStoreProductReq) (*BaseResp, error)
	UnbindStoreProduct(context.Context, *UnbindStoreProductReq) (*BaseResp, error)
	UpdateStoreProductStatus(context.Context, *UpdateStoreProductStatusReq) (*BaseResp, error)
	UpdateStoreProductStock(context.Context, *UpdateStoreProductStockReq) (*BaseResp, error)
	ListStoreProducts(context.Context, *ListStoreProductsReq) (*StoreProductListResp, error)
	AdminListOrders(context.Context, *AdminListOrdersReq) (*OrderListResp, error)
	ShipOrder(context.Context, *ShipOrderReq) (*BaseResp, error)
	AdminCancelOrder(context.Context, *AdminCancelOrderReq) (*BaseResp, error)
	// Internal endpoints
	CancelExpiredOrder(context.Context, *OrderIDReq) (*BaseResp, error)
	DebitWallet(context.Context, *DebitWalletReq) (*DebitWalletResp, error)
	AlipayNotify(context.Context, *AlipayNotifyReq) (*AlipayNotifyResp, error)
	mustEmbedUnimplementedMallRpcServer()
}

// UnimplementedMallRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMallRpcServer struct{}

func (UnimplementedMallRpcServer) ListProducts(context.Context, *ListProductsReq) (*ProductListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedMallRpcServer) SearchProducts(context.Context, *SearchProductsReq) (*ProductListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedMallRpcServer) GetProductDetail(context.Context, *ProductIDReq) (*ProductDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductDetail not implemented")
}
func (UnimplementedMallRpcServer) GetPromotions(context.Context, *ListProductsReq) (*ProductListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPromotions not implemented")
}
func (UnimplementedMallRpcServer) ListStores(context.Context, *ListStoresReq) (*StoreListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedMallRpcServer) GetStoreDetail(context.Context, *StoreIDReq) (*StoreDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreDetail not implemented")
}
func (UnimplementedMallRpcServer) ListCategories(context.Context, *ListCategoriesReq) (*CategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedMallRpcServer) GetCategoryDetail(context.Context, *CategoryIDReq) (*CategoryDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryDetail not implemented")
}
func (UnimplementedMallRpcServer) ListServiceAreas(context.Context, *ListServiceAreasReq) (*ServiceAreaListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceAreas not implemented")
}
func (UnimplementedMallRpcServer) AddCartItem(context.Context, *AddCartItemReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCartItem not implemented")
}
func (UnimplementedMallRpcServer) RemoveCartItem(context.Context, *RemoveCartItemReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCartItem not implemented")
}
func (UnimplementedMallRpcServer) UpdateCartItemQty(context.Context, *UpdateCartItemQtyReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCartItemQty not implemented")
}
func (UnimplementedMallRpcServer) ListCart(context.Context, *UserIDReq) (*CartResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCart not implemented")
}
func (UnimplementedMallRpcServer) AddFavorite(context.Context, *AddFavoriteReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFavorite not implemented")
}
func (UnimplementedMallRpcServer) RemoveFavorite(context.Context, *RemoveFavoriteReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedMallRpcServer) ListFavorites(context.Context, *ListFavoritesReq) (*FavoriteListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFavorites not implemented")
}
func (UnimplementedMallRpcServer) CheckFavorite(context.Context, *CheckFavoriteReq) (*CheckFavoriteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFavorite not implemented")
}
func (UnimplementedMallRpcServer) ListComments(context.Context, *ListCommentsReq) (*CommentListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedMallRpcServer) CreateComment(context.Context, *CreateCommentReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedMallRpcServer) CreateOrder(context.Context, *CreateOrderReq) (*OrderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedMallRpcServer) ListAvailableStores(context.Context, *ListAvailableStoresReq) (*StoreListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableStores not implemented")
}
func (UnimplementedMallRpcServer) PayOrder(context.Context, *PayOrderReq) (*PayOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PayOrder not implemented")
}
func (UnimplementedMallRpcServer) CancelOrder(context.Context, *CancelOrderReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMallRpcServer) ReceiveOrder(context.Context, *OrderIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveOrder not implemented")
}
func (UnimplementedMallRpcServer) GetOrderDetail(context.Context, *OrderIDReq) (*OrderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderDetail not implemented")
}
func (UnimplementedMallRpcServer) GetPaymentStatus(context.Context, *OrderIDReq) (*PaymentStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentStatus not implemented")
}
func (UnimplementedMallRpcServer) ListOrders(context.Context, *ListOrdersReq) (*OrderListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedMallRpcServer) RechargeWallet(context.Context, *RechargeWalletReq) (*RechargeWalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RechargeWallet not implemented")
}
func (UnimplementedMallRpcServer) TransferWallet(context.Context, *TransferWalletReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferWallet not implemented")
}
func (UnimplementedMallRpcServer) GetWalletBalance(context.Context, *UserIDReq) (*WalletBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletBalance not implemented")
}
func (UnimplementedMallRpcServer) ListWalletTransactions(context.Context, *ListWalletTxReq) (*WalletTxListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletTransactions not implemented")
}
func (UnimplementedMallRpcServer) CreateCategory(context.Context, *CreateCategoryReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedMallRpcServer) UpdateCategory(context.Context, *UpdateCategoryReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedMallRpcServer) DeleteCategory(context.Context, *CategoryIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedMallRpcServer) AdminListProducts(context.Context, *AdminListProductsReq) (*ProductListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListProducts not implemented")
}
func (UnimplementedMallRpcServer) CreateProduct(context.Context, *CreateProductReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedMallRpcServer) UpdateProduct(context.Context, *UpdateProductReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedMallRpcServer) DeleteProduct(context.Context, *ProductIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedMallRpcServer) CreateServiceArea(context.Context, *CreateServiceAreaReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceArea not implemented")
}
func (UnimplementedMallRpcServer) UpdateServiceArea(context.Context, *UpdateServiceAreaReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServiceArea not implemented")
}
func (UnimplementedMallRpcServer) DeleteServiceArea(context.Context, *CategoryIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServiceArea not implemented")
}
func (UnimplementedMallRpcServer) CreateStore(context.Context, *CreateStoreReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedMallRpcServer) UpdateStore(context.Context, *UpdateStoreReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStore not implemented")
}
func (UnimplementedMallRpcServer) DeleteStore(context.Context, *StoreIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedMallRpcServer) BindStoreProduct(context.Context, *BindStoreProductReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindStoreProduct not implemented")
}
func (UnimplementedMallRpcServer) UnbindStoreProduct(context.Context, *UnbindStoreProductReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindStoreProduct not implemented")
}
func (UnimplementedMallRpcServer) UpdateStoreProductStatus(context.Context, *UpdateStoreProductStatusReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStoreProductStatus not implemented")
}
func (UnimplementedMallRpcServer) UpdateStoreProductStock(context.Context, *UpdateStoreProductStockReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStoreProductStock not implemented")
}
func (UnimplementedMallRpcServer) ListStoreProducts(context.Context, *ListStoreProductsReq) (*StoreProductListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStoreProducts not implemented")
}
func (UnimplementedMallRpcServer) AdminListOrders(context.Context, *AdminListOrdersReq) (*OrderListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListOrders not implemented")
}
func (UnimplementedMallRpcServer) ShipOrder(context.Context, *ShipOrderReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ShipOrder not implemented")
}
func (UnimplementedMallRpcServer) AdminCancelOrder(context.Context, *AdminCancelOrderReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCancelOrder not implemented")
}
func (UnimplementedMallRpcServer) CancelExpiredOrder(context.Context, *OrderIDReq) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExpiredOrder not implemented")
}
func (UnimplementedMallRpcServer) DebitWallet(context.Context, *DebitWalletReq) (*DebitWalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DebitWallet not implemented")
}
func (UnimplementedMallRpcServer) AlipayNotify(context.Context, *AlipayNotifyReq) (*AlipayNotifyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AlipayNotify not implemented")
}
func (UnimplementedMallRpcServer) mustEmbedUnimplementedMallRpcServer() {}
func (UnimplementedMallRpcServer) testEmbeddedByValue()                 {}

// UnsafeMallRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MallRpcServer will
// result in compilation errors.
type UnsafeMallRpcServer interface {
	mustEmbedUnimplementedMallRpcServer()
}

func RegisterMallRpcServer(s grpc.ServiceRegistrar, srv MallRpcServer) {
	// If the following call panics, it indicates UnimplementedMallRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MallRpc_ServiceDesc, srv)
}

func _MallRpc_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListProducts(ctx, req.(*ListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).SearchProducts(ctx, req.(*SearchProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetProductDetail(ctx, req.(*ProductIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetPromotions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetPromotions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetPromotions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetPromotions(ctx, req.(*ListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListStores(ctx, req.(*ListStoresReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetStoreDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetStoreDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetStoreDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetStoreDetail(ctx, req.(*StoreIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListCategories(ctx, req.(*ListCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetCategoryDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetCategoryDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetCategoryDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetCategoryDetail(ctx, req.(*CategoryIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListServiceAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceAreasReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListServiceAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListServiceAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListServiceAreas(ctx, req.(*ListServiceAreasReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_AddCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCartItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).AddCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_AddCartItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).AddCartItem(ctx, req.(*AddCartItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_RemoveCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCartItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).RemoveCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_RemoveCartItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).RemoveCartItem(ctx, req.(*RemoveCartItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateCartItemQty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartItemQtyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateCartItemQty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateCartItemQty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateCartItemQty(ctx, req.(*UpdateCartItemQtyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListCart(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_AddFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).AddFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_AddFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).AddFavorite(ctx, req.(*AddFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_RemoveFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).RemoveFavorite(ctx, req.(*RemoveFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFavoritesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListFavorites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListFavorites(ctx, req.(*ListFavoritesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CheckFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CheckFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CheckFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CheckFavorite(ctx, req.(*CheckFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListComments(ctx, req.(*ListCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CreateComment(ctx, req.(*CreateCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListAvailableStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableStoresReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListAvailableStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListAvailableStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListAvailableStores(ctx, req.(*ListAvailableStoresReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_PayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).PayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_PayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).PayOrder(ctx, req.(*PayOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ReceiveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ReceiveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ReceiveOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ReceiveOrder(ctx, req.(*OrderIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetOrderDetail(ctx, req.(*OrderIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetPaymentStatus(ctx, req.(*OrderIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListOrders(ctx, req.(*ListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_RechargeWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).RechargeWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_RechargeWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).RechargeWallet(ctx, req.(*RechargeWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_TransferWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).TransferWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_TransferWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).TransferWallet(ctx, req.(*TransferWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_GetWalletBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).GetWalletBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_GetWalletBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).GetWalletBalance(ctx, req.(*UserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListWalletTransactions(ctx, req.(*ListWalletTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CreateCategory(ctx, req.(*CreateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateCategory(ctx, req.(*UpdateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).DeleteCategory(ctx, req.(*CategoryIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_AdminListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).AdminListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_AdminListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).AdminListProducts(ctx, req.(*AdminListProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CreateProduct(ctx, req.(*CreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateProduct(ctx, req.(*UpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).DeleteProduct(ctx, req.(*ProductIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CreateServiceArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceAreaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CreateServiceArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CreateServiceArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CreateServiceArea(ctx, req.(*CreateServiceAreaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateServiceArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceAreaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateServiceArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateServiceArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateServiceArea(ctx, req.(*UpdateServiceAreaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_DeleteServiceArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).DeleteServiceArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_DeleteServiceArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).DeleteServiceArea(ctx, req.(*CategoryIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CreateStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CreateStore(ctx, req.(*CreateStoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateStore(ctx, req.(*UpdateStoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_DeleteStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).DeleteStore(ctx, req.(*StoreIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_BindStoreProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindStoreProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).BindStoreProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_BindStoreProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).BindStoreProduct(ctx, req.(*BindStoreProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UnbindStoreProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindStoreProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UnbindStoreProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UnbindStoreProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UnbindStoreProduct(ctx, req.(*UnbindStoreProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateStoreProductStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreProductStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateStoreProductStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateStoreProductStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateStoreProductStatus(ctx, req.(*UpdateStoreProductStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_UpdateStoreProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreProductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).UpdateStoreProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_UpdateStoreProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).UpdateStoreProductStock(ctx, req.(*UpdateStoreProductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ListStoreProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoreProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ListStoreProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ListStoreProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ListStoreProducts(ctx, req.(*ListStoreProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_AdminListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).AdminListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_AdminListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).AdminListOrders(ctx, req.(*AdminListOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_ShipOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).ShipOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_ShipOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).ShipOrder(ctx, req.(*ShipOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_AdminCancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).AdminCancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_AdminCancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).AdminCancelOrder(ctx, req.(*AdminCancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_CancelExpiredOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).CancelExpiredOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_CancelExpiredOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).CancelExpiredOrder(ctx, req.(*OrderIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_DebitWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).DebitWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_DebitWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).DebitWallet(ctx, req.(*DebitWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallRpc_AlipayNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlipayNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallRpcServer).AlipayNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MallRpc_AlipayNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallRpcServer).AlipayNotify(ctx, req.(*AlipayNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MallRpc_ServiceDesc is the grpc.ServiceDesc for MallRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MallRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mall.MallRpc",
	HandlerType: (*MallRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProducts",
			Handler:    _MallRpc_ListProducts_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _MallRpc_SearchProducts_Handler,
		},
		{
			MethodName: "GetProductDetail",
			Handler:    _MallRpc_GetProductDetail_Handler,
		},
		{
			MethodName: "GetPromotions",
			Handler:    _MallRpc_GetPromotions_Handler,
		},
		{
			MethodName: "ListStores",
			Handler:    _MallRpc_ListStores_Handler,
		},
		{
			MethodName: "GetStoreDetail",
			Handler:    _MallRpc_GetStoreDetail_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _MallRpc_ListCategories_Handler,
		},
		{
			MethodName: "GetCategoryDetail",
			Handler:    _MallRpc_GetCategoryDetail_Handler,
		},
		{
			MethodName: "ListServiceAreas",
			Handler:    _MallRpc_ListServiceAreas_Handler,
		},
		{
			MethodName: "AddCartItem",
			Handler:    _MallRpc_AddCartItem_Handler,
		},
		{
			MethodName: "RemoveCartItem",
			Handler:    _MallRpc_RemoveCartItem_Handler,
		},
		{
			MethodName: "UpdateCartItemQty",
			Handler:    _MallRpc_UpdateCartItemQty_Handler,
		},
		{
			MethodName: "ListCart",
			Handler:    _MallRpc_ListCart_Handler,
		},
		{
			MethodName: "AddFavorite",
			Handler:    _MallRpc_AddFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _MallRpc_RemoveFavorite_Handler,
		},
		{
			MethodName: "ListFavorites",
			Handler:    _MallRpc_ListFavorites_Handler,
		},
		{
			MethodName: "CheckFavorite",
			Handler:    _MallRpc_CheckFavorite_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _MallRpc_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _MallRpc_CreateComment_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _MallRpc_CreateOrder_Handler,
		},
		{
			MethodName: "ListAvailableStores",
			Handler:    _MallRpc_ListAvailableStores_Handler,
		},
		{
			MethodName: "PayOrder",
			Handler:    _MallRpc_PayOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MallRpc_CancelOrder_Handler,
		},
		{
			MethodName: "ReceiveOrder",
			Handler:    _MallRpc_ReceiveOrder_Handler,
		},
		{
			MethodName: "GetOrderDetail",
			Handler:    _MallRpc_GetOrderDetail_Handler,
		},
		{
			MethodName: "GetPaymentStatus",
			Handler:    _MallRpc_GetPaymentStatus_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _MallRpc_ListOrders_Handler,
		},
		{
			MethodName: "RechargeWallet",
			Handler:    _MallRpc_RechargeWallet_Handler,
		},
		{
			MethodName: "TransferWallet",
			Handler:    _MallRpc_TransferWallet_Handler,
		},
		{
			MethodName: "GetWalletBalance",
			Handler:    _MallRpc_GetWalletBalance_Handler,
		},
		{
			MethodName: "ListWalletTransactions",
			Handler:    _MallRpc_ListWalletTransactions_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _MallRpc_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _MallRpc_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _MallRpc_DeleteCategory_Handler,
		},
		{
			MethodName: "AdminListProducts",
			Handler:    _MallRpc_AdminListProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _MallRpc_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _MallRpc_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _MallRpc_DeleteProduct_Handler,
		},
		{
			MethodName: "CreateServiceArea",
			Handler:    _MallRpc_CreateServiceArea_Handler,
		},
		{
			MethodName: "UpdateServiceArea",
			Handler:    _MallRpc_UpdateServiceArea_Handler,
		},
		{
			MethodName: "DeleteServiceArea",
			Handler:    _MallRpc_DeleteServiceArea_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _MallRpc_CreateStore_Handler,
		},
		{
			MethodName: "UpdateStore",
			Handler:    _MallRpc_UpdateStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _MallRpc_DeleteStore_Handler,
		},
		{
			MethodName: "BindStoreProduct",
			Handler:    _MallRpc_BindStoreProduct_Handler,
		},
		{
			MethodName: "UnbindStoreProduct",
			Handler:    _MallRpc_UnbindStoreProduct_Handler,
		},
		{
			MethodName: "UpdateStoreProductStatus",
			Handler:    _MallRpc_UpdateStoreProductStatus_Handler,
		},
		{
			MethodName: "UpdateStoreProductStock",
			Handler:    _MallRpc_UpdateStoreProductStock_Handler,
		},
		{
			MethodName: "ListStoreProducts",
			Handler:    _MallRpc_ListStoreProducts_Handler,
		},
		{
			MethodName: "AdminListOrders",
			Handler:    _MallRpc_AdminListOrders_Handler,
		},
		{
			MethodName: "ShipOrder",
			Handler:    _MallRpc_ShipOrder_Handler,
		},
		{
			MethodName: "AdminCancelOrder",
			Handler:    _MallRpc_AdminCancelOrder_Handler,
		},
		{
			MethodName: "CancelExpiredOrder",
			Handler:    _MallRpc_CancelExpiredOrder_Handler,
		},
		{
			MethodName: "DebitWallet",
			Handler:    _MallRpc_DebitWallet_Handler,
		},
		{
			MethodName: "AlipayNotify",
			Handler:    _MallRpc_AlipayNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/mall/rpc/mall.proto",
}
